// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file octodeck/v1/query.proto (package octodeck.v1, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file octodeck/v1/query.proto.
 */
export const file_octodeck_v1_query: GenFile = /*@__PURE__*/
  fileDesc("ChdvY3RvZGVjay92MS9xdWVyeS5wcm90bxILb2N0b2RlY2sudjEiqAEKBEV4cHISKwoJcHJlZGljYXRlGAEgASgLMhYub2N0b2RlY2sudjEuUHJlZGljYXRlSAASJAoDYW5kGAIgASgLMhUub2N0b2RlY2sudjEuRXhwckxpc3RIABIjCgJvchgDIAEoCzIVLm9jdG9kZWNrLnYxLkV4cHJMaXN0SAASIAoDbm90GAQgASgLMhEub2N0b2RlY2sudjEuRXhwckgAQgYKBGtpbmQiLAoIRXhwckxpc3QSIAoFZXhwcnMYASADKAsyES5vY3RvZGVjay52MS5FeHByIk8KCVByZWRpY2F0ZRIhCgVmaWVsZBgBIAEoDjISLm9jdG9kZWNrLnYxLkZpZWxkEg4KBnZhbHVlcxgCIAMoCRIPCgduZWdhdGVkGAMgASgIIlAKBFNvcnQSIQoDa2V5GAEgASgOMhQub2N0b2RlY2sudjEuU29ydEtleRIlCgVvcmRlchgCIAEoDjIWLm9jdG9kZWNrLnYxLlNvcnRPcmRlciJTCgVGYWNldBIhCgVmaWVsZBgBIAEoDjISLm9jdG9kZWNrLnYxLkZpZWxkEicKBnZhbHVlcxgCIAMoCzIXLm9jdG9kZWNrLnYxLkZhY2V0VmFsdWUicQoKRmFjZXRWYWx1ZRINCgV2YWx1ZRgBIAEoCRINCgVjb3VudBgCIAEoBRINCgVjb2xvchgDIAEoCRI2ChJsYXRlc3RfYWN0aXZpdHlfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIlwKCUV4cHJFcnJvchIMCgRwYXRoGAEgASgJEg8KB21lc3NhZ2UYAiABKAkSIQoFZmllbGQYAyABKA4yEi5vY3RvZGVjay52MS5GaWVsZBINCgV2YWx1ZRgEIAEoCSqvAgoFRmllbGQSFQoRRklFTERfVU5TUEVDSUZJRUQQABIQCgxGSUVMRF9UUklBR0UQARIPCgtGSUVMRF9TVEFURRACEg4KCkZJRUxEX1RZUEUQAxIPCgtGSUVMRF9EUkFGVBAEEhIKDkZJRUxEX1RSQUNLSU5HEAUSEQoNRklFTERfU1RBUlJFRBAGEg0KCUZJRUxEX05FVxAHEg4KCkZJRUxEX1JFUE8QCBINCglGSUVMRF9PUkcQCRIQCgxGSUVMRF9BVVRIT1IQChISCg5GSUVMRF9BU1NJR05FRRALEhMKD0ZJRUxEX01JTEVTVE9ORRAMEg8KC0ZJRUxEX0xBQkVMEA0SDAoIRklFTERfTk8QDhIMCghGSUVMRF9JThAPEg4KCkZJRUxEX1RFWFQQECpjCgdTb3J0S2V5EhgKFFNPUlRfS0VZX1VOU1BFQ0lGSUVEEAASFAoQU09SVF9LRVlfVVBEQVRFRBABEhIKDlNPUlRfS0VZX0FDS0VEEAISFAoQU09SVF9LRVlfQ1JFQVRFRBADKlAKCVNvcnRPcmRlchIaChZTT1JUX09SREVSX1VOU1BFQ0lGSUVEEAASEwoPU09SVF9PUkRFUl9ERVNDEAESEgoOU09SVF9PUkRFUl9BU0MQAkK1AQoPY29tLm9jdG9kZWNrLnYxQgpRdWVyeVByb3RvUAFaSWdpdGh1Yi5jb20vdGFsbGNsYWlyL29jdG9kZWNrL2JhY2tlbmQvaW50ZXJuYWwvYXBpL29jdG9kZWNrL3YxO29jdG9kZWNrdjGiAgNPWFiqAgtPY3RvZGVjay5WMcoCC09jdG9kZWNrXFYx4gIXT2N0b2RlY2tcVjFcR1BCTWV0YWRhdGHqAgxPY3RvZGVjazo6VjFiCGVkaXRpb25zcOgH", [file_google_protobuf_timestamp]);

/**
 * A boolean query over items. An unset Expr (or a root Expr with no kind set) is the empty
 * query, which matches every item before the implicit triage scope is applied.
 *
 * Triage scope: when no FIELD_TRIAGE predicate appears anywhere in the tree (at any depth,
 * negated or not), the server ANDs an implicit `triage:inbox` onto the root. Callers that
 * need every item must send `triage:all`.
 *
 * Validation (InvalidArgument with an ExprError detail): a nested Expr must have a kind set;
 * an `or` list must be non-empty (an empty `and` list is true); `not` must have its child set.
 *
 * @generated from message octodeck.v1.Expr
 */
export type Expr = Message<"octodeck.v1.Expr"> & {
  /**
   * @generated from oneof octodeck.v1.Expr.kind
   */
  kind: {
    /**
     * @generated from field: octodeck.v1.Predicate predicate = 1;
     */
    value: Predicate;
    case: "predicate";
  } | {
    /**
     * All children must match. An empty list matches every item.
     *
     * @generated from field: octodeck.v1.ExprList and = 2;
     */
    value: ExprList;
    case: "and";
  } | {
    /**
     * At least one child must match. Must be non-empty.
     *
     * @generated from field: octodeck.v1.ExprList or = 3;
     */
    value: ExprList;
    case: "or";
  } | {
    /**
     * The child must not match.
     *
     * @generated from field: octodeck.v1.Expr not = 4;
     */
    value: Expr;
    case: "not";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message octodeck.v1.Expr.
 * Use `create(ExprSchema)` to create a new message.
 */
export const ExprSchema: GenMessage<Expr> = /*@__PURE__*/
  messageDesc(file_octodeck_v1_query, 0);

/**
 * @generated from message octodeck.v1.ExprList
 */
export type ExprList = Message<"octodeck.v1.ExprList"> & {
  /**
   * @generated from field: repeated octodeck.v1.Expr exprs = 1;
   */
  exprs: Expr[];
};

/**
 * Describes the message octodeck.v1.ExprList.
 * Use `create(ExprListSchema)` to create a new message.
 */
export const ExprListSchema: GenMessage<ExprList> = /*@__PURE__*/
  messageDesc(file_octodeck_v1_query, 1);

/**
 * One condition on one field: `field:v1,v2` (v1 OR v2), or `-field:v1,v2` when negated
 * (neither v1 nor v2). Repeating a predicate for the same field ANDs them.
 *
 * @generated from message octodeck.v1.Predicate
 */
export type Predicate = Message<"octodeck.v1.Predicate"> & {
  /**
   * Must be a known value other than FIELD_UNSPECIFIED.
   *
   * @generated from field: octodeck.v1.Field field = 1;
   */
  field: Field;

  /**
   * ORed together. Must be non-empty; every value must be non-empty after trimming.
   * All values are case-insensitive. Closed fields accept only the values documented on
   * their Field enum value.
   *
   * @generated from field: repeated string values = 2;
   */
  values: string[];

  /**
   * Negates the whole OR of values.
   *
   * @generated from field: bool negated = 3;
   */
  negated: boolean;
};

/**
 * Describes the message octodeck.v1.Predicate.
 * Use `create(PredicateSchema)` to create a new message.
 */
export const PredicateSchema: GenMessage<Predicate> = /*@__PURE__*/
  messageDesc(file_octodeck_v1_query, 2);

/**
 * Result ordering for GetItems. Starred items always come first.
 *
 * @generated from message octodeck.v1.Sort
 */
export type Sort = Message<"octodeck.v1.Sort"> & {
  /**
   * @generated from field: octodeck.v1.SortKey key = 1;
   */
  key: SortKey;

  /**
   * @generated from field: octodeck.v1.SortOrder order = 2;
   */
  order: SortOrder;
};

/**
 * Describes the message octodeck.v1.Sort.
 * Use `create(SortSchema)` to create a new message.
 */
export const SortSchema: GenMessage<Sort> = /*@__PURE__*/
  messageDesc(file_octodeck_v1_query, 3);

/**
 * The available values of one field, with counts. See GetFacetsRequest.
 *
 * @generated from message octodeck.v1.Facet
 */
export type Facet = Message<"octodeck.v1.Facet"> & {
  /**
   * @generated from field: octodeck.v1.Field field = 1;
   */
  field: Field;

  /**
   * @generated from field: repeated octodeck.v1.FacetValue values = 2;
   */
  values: FacetValue[];
};

/**
 * Describes the message octodeck.v1.Facet.
 * Use `create(FacetSchema)` to create a new message.
 */
export const FacetSchema: GenMessage<Facet> = /*@__PURE__*/
  messageDesc(file_octodeck_v1_query, 4);

/**
 * @generated from message octodeck.v1.FacetValue
 */
export type FacetValue = Message<"octodeck.v1.FacetValue"> & {
  /**
   * Canonical value (lower-case for closed fields; first-seen casing for open fields).
   *
   * @generated from field: string value = 1;
   */
  value: string;

  /**
   * Number of matching items with this value. May be 0.
   *
   * @generated from field: int32 count = 2;
   */
  count: number;

  /**
   * FIELD_LABEL only: the label color (hex, without '#').
   *
   * @generated from field: string color = 3;
   */
  color: string;

  /**
   * FIELD_REPO only: latest non-noise activity across the repo's items.
   *
   * @generated from field: google.protobuf.Timestamp latest_activity_at = 4;
   */
  latestActivityAt?: Timestamp | undefined;
};

/**
 * Describes the message octodeck.v1.FacetValue.
 * Use `create(FacetValueSchema)` to create a new message.
 */
export const FacetValueSchema: GenMessage<FacetValue> = /*@__PURE__*/
  messageDesc(file_octodeck_v1_query, 5);

/**
 * Attached as a detail to InvalidArgument errors returned for an invalid Expr.
 *
 * @generated from message octodeck.v1.ExprError
 */
export type ExprError = Message<"octodeck.v1.ExprError"> & {
  /**
   * Proto field path from the root Expr to the offending node, e.g.
   * "and.exprs[2].not.predicate.values[0]". Empty for the root.
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * Human-readable description of the problem.
   *
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * Field of the offending predicate, if any.
   *
   * @generated from field: octodeck.v1.Field field = 3;
   */
  field: Field;

  /**
   * Offending value, if any.
   *
   * @generated from field: string value = 4;
   */
  value: string;
};

/**
 * Describes the message octodeck.v1.ExprError.
 * Use `create(ExprErrorSchema)` to create a new message.
 */
export const ExprErrorSchema: GenMessage<ExprError> = /*@__PURE__*/
  messageDesc(file_octodeck_v1_query, 6);

/**
 * The query vocabulary. This enum and its comments are the single source of truth for the
 * fields and the legal values of closed fields. "Closed" fields reject any other value with
 * InvalidArgument; "open" fields accept any non-empty string.
 *
 * @generated from enum octodeck.v1.Field
 */
export enum Field {
  /**
   * @generated from enum value: FIELD_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Closed: "inbox" (computed status is not ACKED), "acked" (status is ACKED),
   * "all" (= inbox,acked). Implicit "inbox" when no triage predicate is present.
   *
   * @generated from enum value: FIELD_TRIAGE = 1;
   */
  TRIAGE = 1,

  /**
   * Closed: "open" (OPEN or unspecified), "closed" (CLOSED or MERGED), "merged" (MERGED).
   *
   * @generated from enum value: FIELD_STATE = 2;
   */
  STATE = 2,

  /**
   * Closed: "pr", "issue". Items with an unspecified type fall back to the URL
   * ("/pull/" or "/issues/").
   *
   * @generated from enum value: FIELD_TYPE = 3;
   */
  TYPE = 3,

  /**
   * Closed: "true", "false". Matches Item.is_draft.
   *
   * @generated from enum value: FIELD_DRAFT = 4;
   */
  DRAFT = 4,

  /**
   * Closed: "true" (subscription is not UNSUBSCRIBED), "false" (UNSUBSCRIBED).
   *
   * @generated from enum value: FIELD_TRACKING = 5;
   */
  TRACKING = 5,

  /**
   * Closed: "true", "false". Matches ItemLocalState.starred.
   *
   * @generated from enum value: FIELD_STARRED = 6;
   */
  STARRED = 6,

  /**
   * Closed: "item" (never viewed), "mention", "comment" (comments, reviews and state
   * changes), "code", "noise", "any" (= item,mention,comment,code; never noise).
   * Flags are independent: one item can match several values. Acked items have none.
   *
   * @generated from enum value: FIELD_NEW = 7;
   */
  NEW = 7,

  /**
   * Open: "owner/name", compared case-insensitively with Item.repo.
   *
   * @generated from enum value: FIELD_REPO = 8;
   */
  REPO = 8,

  /**
   * Open: "owner"; matches items whose repo is "owner/<anything>".
   *
   * @generated from enum value: FIELD_ORG = 9;
   */
  ORG = 9,

  /**
   * Open: a login, or "@me" for the authenticated user (matches nothing if unknown).
   *
   * @generated from enum value: FIELD_AUTHOR = 10;
   */
  AUTHOR = 10,

  /**
   * Open: a login, or "@me"; matches if any assignee has that login.
   *
   * @generated from enum value: FIELD_ASSIGNEE = 11;
   */
  ASSIGNEE = 11,

  /**
   * Open: a milestone title.
   *
   * @generated from enum value: FIELD_MILESTONE = 12;
   */
  MILESTONE = 12,

  /**
   * Open: a label name; matches if any visible label has that name.
   *
   * @generated from enum value: FIELD_LABEL = 13;
   */
  LABEL = 13,

  /**
   * Closed: "assignee", "label", "milestone"; matches items with none of that field.
   *
   * @generated from enum value: FIELD_NO = 14;
   */
  NO = 14,

  /**
   * Closed: "title", "body". Narrows which fields FIELD_TEXT terms search (default: both).
   * Must not be negated. Always matches on its own.
   *
   * @generated from enum value: FIELD_IN = 15;
   */
  IN = 15,

  /**
   * Open: one free-text term (a word or a phrase), matched as a case-insensitive substring
   * of the title or body. A term of the form "123" or "#123" also matches item number 123.
   *
   * @generated from enum value: FIELD_TEXT = 16;
   */
  TEXT = 16,
}

/**
 * Describes the enum octodeck.v1.Field.
 */
export const FieldSchema: GenEnum<Field> = /*@__PURE__*/
  enumDesc(file_octodeck_v1_query, 0);

/**
 * @generated from enum octodeck.v1.SortKey
 */
export enum SortKey {
  /**
   * Same as SORT_KEY_UPDATED.
   *
   * @generated from enum value: SORT_KEY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Latest non-noise activity.
   *
   * @generated from enum value: SORT_KEY_UPDATED = 1;
   */
  UPDATED = 1,

  /**
   * Time the item was acked (items never acked sort as oldest).
   *
   * @generated from enum value: SORT_KEY_ACKED = 2;
   */
  ACKED = 2,

  /**
   * Creation time (falls back to the update time).
   *
   * @generated from enum value: SORT_KEY_CREATED = 3;
   */
  CREATED = 3,
}

/**
 * Describes the enum octodeck.v1.SortKey.
 */
export const SortKeySchema: GenEnum<SortKey> = /*@__PURE__*/
  enumDesc(file_octodeck_v1_query, 1);

/**
 * @generated from enum octodeck.v1.SortOrder
 */
export enum SortOrder {
  /**
   * Same as SORT_ORDER_DESC.
   *
   * @generated from enum value: SORT_ORDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SORT_ORDER_DESC = 1;
   */
  DESC = 1,

  /**
   * @generated from enum value: SORT_ORDER_ASC = 2;
   */
  ASC = 2,
}

/**
 * Describes the enum octodeck.v1.SortOrder.
 */
export const SortOrderSchema: GenEnum<SortOrder> = /*@__PURE__*/
  enumDesc(file_octodeck_v1_query, 2);

