// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file octodeck/v1/service.proto (package octodeck.v1, edition 2023)
/* eslint-disable */

import { OctoDeckService } from "./service_pb";

/**
 * Main Dashboard Data
 *
 * @generated from rpc octodeck.v1.OctoDeckService.GetItems
 */
export const getItems = OctoDeckService.method.getItems;

/**
 * @generated from rpc octodeck.v1.OctoDeckService.GetItem
 */
export const getItem = OctoDeckService.method.getItem;

/**
 * Actions
 *
 * @generated from rpc octodeck.v1.OctoDeckService.ViewItem
 */
export const viewItem = OctoDeckService.method.viewItem;

/**
 * @generated from rpc octodeck.v1.OctoDeckService.AckItem
 */
export const ackItem = OctoDeckService.method.ackItem;

/**
 * @generated from rpc octodeck.v1.OctoDeckService.StarItem
 */
export const starItem = OctoDeckService.method.starItem;

/**
 * @generated from rpc octodeck.v1.OctoDeckService.SetNotes
 */
export const setNotes = OctoDeckService.method.setNotes;

/**
 * @generated from rpc octodeck.v1.OctoDeckService.RefetchItem
 */
export const refetchItem = OctoDeckService.method.refetchItem;

/**
 * @generated from rpc octodeck.v1.OctoDeckService.DeleteItem
 */
export const deleteItem = OctoDeckService.method.deleteItem;

/**
 * Synchronization Status & Traces
 *
 * @generated from rpc octodeck.v1.OctoDeckService.GetSyncStatus
 */
export const getSyncStatus = OctoDeckService.method.getSyncStatus;

/**
 * @generated from rpc octodeck.v1.OctoDeckService.GetSyncTraces
 */
export const getSyncTraces = OctoDeckService.method.getSyncTraces;

/**
 * Database & Storage Observability
 *
 * @generated from rpc octodeck.v1.OctoDeckService.GetDatabaseStats
 */
export const getDatabaseStats = OctoDeckService.method.getDatabaseStats;

/**
 * Configuration
 *
 * @generated from rpc octodeck.v1.OctoDeckService.GetConfig
 */
export const getConfig = OctoDeckService.method.getConfig;

/**
 * @generated from rpc octodeck.v1.OctoDeckService.UpdateConfig
 */
export const updateConfig = OctoDeckService.method.updateConfig;
