// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: octodeck/v1/query.proto

package octodeckv1

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The query vocabulary. This enum and its comments are the single source of truth for the
// fields and the legal values of closed fields. "Closed" fields reject any other value with
// InvalidArgument; "open" fields accept any non-empty string.
type Field int32

const (
	Field_FIELD_UNSPECIFIED Field = 0
	// Closed: "inbox" (computed status is not ACKED), "acked" (status is ACKED),
	// "all" (= inbox,acked). Implicit "inbox" when no triage predicate is present.
	Field_FIELD_TRIAGE Field = 1
	// Closed: "open" (OPEN or unspecified), "closed" (CLOSED or MERGED), "merged" (MERGED).
	Field_FIELD_STATE Field = 2
	// Closed: "pr", "issue". Items with an unspecified type fall back to the URL
	// ("/pull/" or "/issues/").
	Field_FIELD_TYPE Field = 3
	// Closed: "true", "false". Matches Item.is_draft.
	Field_FIELD_DRAFT Field = 4
	// Closed: "true" (subscription is not UNSUBSCRIBED), "false" (UNSUBSCRIBED).
	Field_FIELD_TRACKING Field = 5
	// Closed: "true", "false". Matches ItemLocalState.starred.
	Field_FIELD_STARRED Field = 6
	// Closed: "item" (never viewed), "mention", "comment" (comments, reviews and state
	// changes), "code", "noise", "any" (= item,mention,comment,code; never noise).
	// Flags are independent: one item can match several values. Acked items have none.
	Field_FIELD_NEW Field = 7
	// Open: "owner/name", compared case-insensitively with Item.repo.
	Field_FIELD_REPO Field = 8
	// Open: "owner"; matches items whose repo is "owner/<anything>".
	Field_FIELD_ORG Field = 9
	// Open: a login, or "@me" for the authenticated user (matches nothing if unknown).
	Field_FIELD_AUTHOR Field = 10
	// Open: a login, or "@me"; matches if any assignee has that login.
	Field_FIELD_ASSIGNEE Field = 11
	// Open: a milestone title.
	Field_FIELD_MILESTONE Field = 12
	// Open: a label name; matches if any visible label has that name.
	Field_FIELD_LABEL Field = 13
	// Closed: "assignee", "label", "milestone"; matches items with none of that field.
	Field_FIELD_NO Field = 14
	// Closed: "title", "body". Narrows which fields FIELD_TEXT terms search (default: both).
	// Must not be negated. Always matches on its own.
	Field_FIELD_IN Field = 15
	// Open: one free-text term (a word or a phrase), matched as a case-insensitive substring
	// of the title or body. A term of the form "123" or "#123" also matches item number 123.
	Field_FIELD_TEXT Field = 16
)

// Enum value maps for Field.
var (
	Field_name = map[int32]string{
		0:  "FIELD_UNSPECIFIED",
		1:  "FIELD_TRIAGE",
		2:  "FIELD_STATE",
		3:  "FIELD_TYPE",
		4:  "FIELD_DRAFT",
		5:  "FIELD_TRACKING",
		6:  "FIELD_STARRED",
		7:  "FIELD_NEW",
		8:  "FIELD_REPO",
		9:  "FIELD_ORG",
		10: "FIELD_AUTHOR",
		11: "FIELD_ASSIGNEE",
		12: "FIELD_MILESTONE",
		13: "FIELD_LABEL",
		14: "FIELD_NO",
		15: "FIELD_IN",
		16: "FIELD_TEXT",
	}
	Field_value = map[string]int32{
		"FIELD_UNSPECIFIED": 0,
		"FIELD_TRIAGE":      1,
		"FIELD_STATE":       2,
		"FIELD_TYPE":        3,
		"FIELD_DRAFT":       4,
		"FIELD_TRACKING":    5,
		"FIELD_STARRED":     6,
		"FIELD_NEW":         7,
		"FIELD_REPO":        8,
		"FIELD_ORG":         9,
		"FIELD_AUTHOR":      10,
		"FIELD_ASSIGNEE":    11,
		"FIELD_MILESTONE":   12,
		"FIELD_LABEL":       13,
		"FIELD_NO":          14,
		"FIELD_IN":          15,
		"FIELD_TEXT":        16,
	}
)

func (x Field) Enum() *Field {
	p := new(Field)
	*p = x
	return p
}

func (x Field) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field) Descriptor() protoreflect.EnumDescriptor {
	return file_octodeck_v1_query_proto_enumTypes[0].Descriptor()
}

func (Field) Type() protoreflect.EnumType {
	return &file_octodeck_v1_query_proto_enumTypes[0]
}

func (x Field) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SortKey int32

const (
	// Same as SORT_KEY_UPDATED.
	SortKey_SORT_KEY_UNSPECIFIED SortKey = 0
	// Latest non-noise activity.
	SortKey_SORT_KEY_UPDATED SortKey = 1
	// Time the item was acked (items never acked sort as oldest).
	SortKey_SORT_KEY_ACKED SortKey = 2
	// Creation time (falls back to the update time).
	SortKey_SORT_KEY_CREATED SortKey = 3
)

// Enum value maps for SortKey.
var (
	SortKey_name = map[int32]string{
		0: "SORT_KEY_UNSPECIFIED",
		1: "SORT_KEY_UPDATED",
		2: "SORT_KEY_ACKED",
		3: "SORT_KEY_CREATED",
	}
	SortKey_value = map[string]int32{
		"SORT_KEY_UNSPECIFIED": 0,
		"SORT_KEY_UPDATED":     1,
		"SORT_KEY_ACKED":       2,
		"SORT_KEY_CREATED":     3,
	}
)

func (x SortKey) Enum() *SortKey {
	p := new(SortKey)
	*p = x
	return p
}

func (x SortKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortKey) Descriptor() protoreflect.EnumDescriptor {
	return file_octodeck_v1_query_proto_enumTypes[1].Descriptor()
}

func (SortKey) Type() protoreflect.EnumType {
	return &file_octodeck_v1_query_proto_enumTypes[1]
}

func (x SortKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SortOrder int32

const (
	// Same as SORT_ORDER_DESC.
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_DESC        SortOrder = 1
	SortOrder_SORT_ORDER_ASC         SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_DESC",
		2: "SORT_ORDER_ASC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_DESC":        1,
		"SORT_ORDER_ASC":         2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_octodeck_v1_query_proto_enumTypes[2].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_octodeck_v1_query_proto_enumTypes[2]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// A boolean query over items. An unset Expr (or a root Expr with no kind set) is the empty
// query, which matches every item before the implicit triage scope is applied.
//
// Triage scope: when no FIELD_TRIAGE predicate appears anywhere in the tree (at any depth,
// negated or not), the server ANDs an implicit `triage:inbox` onto the root. Callers that
// need every item must send `triage:all`.
//
// Validation (InvalidArgument with an ExprError detail): a nested Expr must have a kind set;
// an `or` list must be non-empty (an empty `and` list is true); `not` must have its child set.
type Expr struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind isExpr_Kind            `protobuf_oneof:"kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Expr) Reset() {
	*x = Expr{}
	mi := &file_octodeck_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr) ProtoMessage() {}

func (x *Expr) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Expr) GetPredicate() *Predicate {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*expr_Predicate); ok {
			return x.Predicate
		}
	}
	return nil
}

func (x *Expr) GetAnd() *ExprList {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*expr_And); ok {
			return x.And
		}
	}
	return nil
}

func (x *Expr) GetOr() *ExprList {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*expr_Or); ok {
			return x.Or
		}
	}
	return nil
}

func (x *Expr) GetNot() *Expr {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*expr_Not); ok {
			return x.Not
		}
	}
	return nil
}

func (x *Expr) SetPredicate(v *Predicate) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &expr_Predicate{v}
}

func (x *Expr) SetAnd(v *ExprList) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &expr_And{v}
}

func (x *Expr) SetOr(v *ExprList) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &expr_Or{v}
}

func (x *Expr) SetNot(v *Expr) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &expr_Not{v}
}

func (x *Expr) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Expr) HasPredicate() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*expr_Predicate)
	return ok
}

func (x *Expr) HasAnd() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*expr_And)
	return ok
}

func (x *Expr) HasOr() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*expr_Or)
	return ok
}

func (x *Expr) HasNot() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*expr_Not)
	return ok
}

func (x *Expr) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Expr) ClearPredicate() {
	if _, ok := x.xxx_hidden_Kind.(*expr_Predicate); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Expr) ClearAnd() {
	if _, ok := x.xxx_hidden_Kind.(*expr_And); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Expr) ClearOr() {
	if _, ok := x.xxx_hidden_Kind.(*expr_Or); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Expr) ClearNot() {
	if _, ok := x.xxx_hidden_Kind.(*expr_Not); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Expr_Kind_not_set_case case_Expr_Kind = 0
const Expr_Predicate_case case_Expr_Kind = 1
const Expr_And_case case_Expr_Kind = 2
const Expr_Or_case case_Expr_Kind = 3
const Expr_Not_case case_Expr_Kind = 4

func (x *Expr) WhichKind() case_Expr_Kind {
	if x == nil {
		return Expr_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *expr_Predicate:
		return Expr_Predicate_case
	case *expr_And:
		return Expr_And_case
	case *expr_Or:
		return Expr_Or_case
	case *expr_Not:
		return Expr_Not_case
	default:
		return Expr_Kind_not_set_case
	}
}

type Expr_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Kind:
	Predicate *Predicate
	// All children must match. An empty list matches every item.
	And *ExprList
	// At least one child must match. Must be non-empty.
	Or *ExprList
	// The child must not match.
	Not *Expr
	// -- end of xxx_hidden_Kind
}

func (b0 Expr_builder) Build() *Expr {
	m0 := &Expr{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Predicate != nil {
		x.xxx_hidden_Kind = &expr_Predicate{b.Predicate}
	}
	if b.And != nil {
		x.xxx_hidden_Kind = &expr_And{b.And}
	}
	if b.Or != nil {
		x.xxx_hidden_Kind = &expr_Or{b.Or}
	}
	if b.Not != nil {
		x.xxx_hidden_Kind = &expr_Not{b.Not}
	}
	return m0
}

type case_Expr_Kind protoreflect.FieldNumber

func (x case_Expr_Kind) String() string {
	md := file_octodeck_v1_query_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isExpr_Kind interface {
	isExpr_Kind()
}

type expr_Predicate struct {
	Predicate *Predicate `protobuf:"bytes,1,opt,name=predicate,oneof"`
}

type expr_And struct {
	// All children must match. An empty list matches every item.
	And *ExprList `protobuf:"bytes,2,opt,name=and,oneof"`
}

type expr_Or struct {
	// At least one child must match. Must be non-empty.
	Or *ExprList `protobuf:"bytes,3,opt,name=or,oneof"`
}

type expr_Not struct {
	// The child must not match.
	Not *Expr `protobuf:"bytes,4,opt,name=not,oneof"`
}

func (*expr_Predicate) isExpr_Kind() {}

func (*expr_And) isExpr_Kind() {}

func (*expr_Or) isExpr_Kind() {}

func (*expr_Not) isExpr_Kind() {}

type ExprList struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Exprs *[]*Expr               `protobuf:"bytes,1,rep,name=exprs"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExprList) Reset() {
	*x = ExprList{}
	mi := &file_octodeck_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExprList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExprList) ProtoMessage() {}

func (x *ExprList) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExprList) GetExprs() []*Expr {
	if x != nil {
		if x.xxx_hidden_Exprs != nil {
			return *x.xxx_hidden_Exprs
		}
	}
	return nil
}

func (x *ExprList) SetExprs(v []*Expr) {
	x.xxx_hidden_Exprs = &v
}

type ExprList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Exprs []*Expr
}

func (b0 ExprList_builder) Build() *ExprList {
	m0 := &ExprList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Exprs = &b.Exprs
	return m0
}

// One condition on one field: `field:v1,v2` (v1 OR v2), or `-field:v1,v2` when negated
// (neither v1 nor v2). Repeating a predicate for the same field ANDs them.
type Predicate struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Field       Field                  `protobuf:"varint,1,opt,name=field,enum=octodeck.v1.Field"`
	xxx_hidden_Values      []string               `protobuf:"bytes,2,rep,name=values"`
	xxx_hidden_Negated     bool                   `protobuf:"varint,3,opt,name=negated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Predicate) Reset() {
	*x = Predicate{}
	mi := &file_octodeck_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Predicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Predicate) ProtoMessage() {}

func (x *Predicate) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Predicate) GetField() Field {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Field
		}
	}
	return Field_FIELD_UNSPECIFIED
}

func (x *Predicate) GetValues() []string {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *Predicate) GetNegated() bool {
	if x != nil {
		return x.xxx_hidden_Negated
	}
	return false
}

func (x *Predicate) SetField(v Field) {
	x.xxx_hidden_Field = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Predicate) SetValues(v []string) {
	x.xxx_hidden_Values = v
}

func (x *Predicate) SetNegated(v bool) {
	x.xxx_hidden_Negated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Predicate) HasField() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Predicate) HasNegated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Predicate) ClearField() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Field = Field_FIELD_UNSPECIFIED
}

func (x *Predicate) ClearNegated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Negated = false
}

type Predicate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Must be a known value other than FIELD_UNSPECIFIED.
	Field *Field
	// ORed together. Must be non-empty; every value must be non-empty after trimming.
	// All values are case-insensitive. Closed fields accept only the values documented on
	// their Field enum value.
	Values []string
	// Negates the whole OR of values.
	Negated *bool
}

func (b0 Predicate_builder) Build() *Predicate {
	m0 := &Predicate{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Field != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Field = *b.Field
	}
	x.xxx_hidden_Values = b.Values
	if b.Negated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Negated = *b.Negated
	}
	return m0
}

// Result ordering for GetItems. Starred items always come first.
type Sort struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         SortKey                `protobuf:"varint,1,opt,name=key,enum=octodeck.v1.SortKey"`
	xxx_hidden_Order       SortOrder              `protobuf:"varint,2,opt,name=order,enum=octodeck.v1.SortOrder"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_octodeck_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Sort) GetKey() SortKey {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Key
		}
	}
	return SortKey_SORT_KEY_UNSPECIFIED
}

func (x *Sort) GetOrder() SortOrder {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Order
		}
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

func (x *Sort) SetKey(v SortKey) {
	x.xxx_hidden_Key = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Sort) SetOrder(v SortOrder) {
	x.xxx_hidden_Order = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Sort) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Sort) HasOrder() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Sort) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Key = SortKey_SORT_KEY_UNSPECIFIED
}

func (x *Sort) ClearOrder() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Order = SortOrder_SORT_ORDER_UNSPECIFIED
}

type Sort_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   *SortKey
	Order *SortOrder
}

func (b0 Sort_builder) Build() *Sort {
	m0 := &Sort{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Key = *b.Key
	}
	if b.Order != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Order = *b.Order
	}
	return m0
}

// The available values of one field, with counts. See GetFacetsRequest.
type Facet struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Field       Field                  `protobuf:"varint,1,opt,name=field,enum=octodeck.v1.Field"`
	xxx_hidden_Values      *[]*FacetValue         `protobuf:"bytes,2,rep,name=values"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Facet) Reset() {
	*x = Facet{}
	mi := &file_octodeck_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facet) ProtoMessage() {}

func (x *Facet) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Facet) GetField() Field {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Field
		}
	}
	return Field_FIELD_UNSPECIFIED
}

func (x *Facet) GetValues() []*FacetValue {
	if x != nil {
		if x.xxx_hidden_Values != nil {
			return *x.xxx_hidden_Values
		}
	}
	return nil
}

func (x *Facet) SetField(v Field) {
	x.xxx_hidden_Field = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Facet) SetValues(v []*FacetValue) {
	x.xxx_hidden_Values = &v
}

func (x *Facet) HasField() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Facet) ClearField() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Field = Field_FIELD_UNSPECIFIED
}

type Facet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Field  *Field
	Values []*FacetValue
}

func (b0 Facet_builder) Build() *Facet {
	m0 := &Facet{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Field != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Field = *b.Field
	}
	x.xxx_hidden_Values = &b.Values
	return m0
}

type FacetValue struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value            *string                `protobuf:"bytes,1,opt,name=value"`
	xxx_hidden_Count            int32                  `protobuf:"varint,2,opt,name=count"`
	xxx_hidden_Color            *string                `protobuf:"bytes,3,opt,name=color"`
	xxx_hidden_LatestActivityAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=latest_activity_at,json=latestActivityAt"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *FacetValue) Reset() {
	*x = FacetValue{}
	mi := &file_octodeck_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacetValue) ProtoMessage() {}

func (x *FacetValue) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FacetValue) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *FacetValue) GetCount() int32 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *FacetValue) GetColor() string {
	if x != nil {
		if x.xxx_hidden_Color != nil {
			return *x.xxx_hidden_Color
		}
		return ""
	}
	return ""
}

func (x *FacetValue) GetLatestActivityAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LatestActivityAt
	}
	return nil
}

func (x *FacetValue) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *FacetValue) SetCount(v int32) {
	x.xxx_hidden_Count = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *FacetValue) SetColor(v string) {
	x.xxx_hidden_Color = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *FacetValue) SetLatestActivityAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_LatestActivityAt = v
}

func (x *FacetValue) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FacetValue) HasCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FacetValue) HasColor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FacetValue) HasLatestActivityAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LatestActivityAt != nil
}

func (x *FacetValue) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Value = nil
}

func (x *FacetValue) ClearCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Count = 0
}

func (x *FacetValue) ClearColor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Color = nil
}

func (x *FacetValue) ClearLatestActivityAt() {
	x.xxx_hidden_LatestActivityAt = nil
}

type FacetValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Canonical value (lower-case for closed fields; first-seen casing for open fields).
	Value *string
	// Number of matching items with this value. May be 0.
	Count *int32
	// FIELD_LABEL only: the label color (hex, without '#').
	Color *string
	// FIELD_REPO only: latest non-noise activity across the repo's items.
	LatestActivityAt *timestamppb.Timestamp
}

func (b0 FacetValue_builder) Build() *FacetValue {
	m0 := &FacetValue{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Value = b.Value
	}
	if b.Count != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Count = *b.Count
	}
	if b.Color != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Color = b.Color
	}
	x.xxx_hidden_LatestActivityAt = b.LatestActivityAt
	return m0
}

// Attached as a detail to InvalidArgument errors returned for an invalid Expr.
type ExprError struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path        *string                `protobuf:"bytes,1,opt,name=path"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	xxx_hidden_Field       Field                  `protobuf:"varint,3,opt,name=field,enum=octodeck.v1.Field"`
	xxx_hidden_Value       *string                `protobuf:"bytes,4,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExprError) Reset() {
	*x = ExprError{}
	mi := &file_octodeck_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExprError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExprError) ProtoMessage() {}

func (x *ExprError) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExprError) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *ExprError) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ExprError) GetField() Field {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Field
		}
	}
	return Field_FIELD_UNSPECIFIED
}

func (x *ExprError) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *ExprError) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ExprError) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ExprError) SetField(v Field) {
	x.xxx_hidden_Field = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ExprError) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ExprError) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ExprError) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ExprError) HasField() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ExprError) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ExprError) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Path = nil
}

func (x *ExprError) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

func (x *ExprError) ClearField() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Field = Field_FIELD_UNSPECIFIED
}

func (x *ExprError) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Value = nil
}

type ExprError_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Proto field path from the root Expr to the offending node, e.g.
	// "and.exprs[2].not.predicate.values[0]". Empty for the root.
	Path *string
	// Human-readable description of the problem.
	Message *string
	// Field of the offending predicate, if any.
	Field *Field
	// Offending value, if any.
	Value *string
}

func (b0 ExprError_builder) Build() *ExprError {
	m0 := &ExprError{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Path = b.Path
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Message = b.Message
	}
	if b.Field != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Field = *b.Field
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

var File_octodeck_v1_query_proto protoreflect.FileDescriptor

const file_octodeck_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x17octodeck/v1/query.proto\x12\voctodeck.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x01\n" +
	"\x04Expr\x126\n" +
	"\tpredicate\x18\x01 \x01(\v2\x16.octodeck.v1.PredicateH\x00R\tpredicate\x12)\n" +
	"\x03and\x18\x02 \x01(\v2\x15.octodeck.v1.ExprListH\x00R\x03and\x12'\n" +
	"\x02or\x18\x03 \x01(\v2\x15.octodeck.v1.ExprListH\x00R\x02or\x12%\n" +
	"\x03not\x18\x04 \x01(\v2\x11.octodeck.v1.ExprH\x00R\x03notB\x06\n" +
	"\x04kind\"3\n" +
	"\bExprList\x12'\n" +
	"\x05exprs\x18\x01 \x03(\v2\x11.octodeck.v1.ExprR\x05exprs\"g\n" +
	"\tPredicate\x12(\n" +
	"\x05field\x18\x01 \x01(\x0e2\x12.octodeck.v1.FieldR\x05field\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\x12\x18\n" +
	"\anegated\x18\x03 \x01(\bR\anegated\"\\\n" +
	"\x04Sort\x12&\n" +
	"\x03key\x18\x01 \x01(\x0e2\x14.octodeck.v1.SortKeyR\x03key\x12,\n" +
	"\x05order\x18\x02 \x01(\x0e2\x16.octodeck.v1.SortOrderR\x05order\"b\n" +
	"\x05Facet\x12(\n" +
	"\x05field\x18\x01 \x01(\x0e2\x12.octodeck.v1.FieldR\x05field\x12/\n" +
	"\x06values\x18\x02 \x03(\v2\x17.octodeck.v1.FacetValueR\x06values\"\x98\x01\n" +
	"\n" +
	"FacetValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12H\n" +
	"\x12latest_activity_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10latestActivityAt\"y\n" +
	"\tExprError\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x05field\x18\x03 \x01(\x0e2\x12.octodeck.v1.FieldR\x05field\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value*\xaf\x02\n" +
	"\x05Field\x12\x15\n" +
	"\x11FIELD_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fFIELD_TRIAGE\x10\x01\x12\x0f\n" +
	"\vFIELD_STATE\x10\x02\x12\x0e\n" +
	"\n" +
	"FIELD_TYPE\x10\x03\x12\x0f\n" +
	"\vFIELD_DRAFT\x10\x04\x12\x12\n" +
	"\x0eFIELD_TRACKING\x10\x05\x12\x11\n" +
	"\rFIELD_STARRED\x10\x06\x12\r\n" +
	"\tFIELD_NEW\x10\a\x12\x0e\n" +
	"\n" +
	"FIELD_REPO\x10\b\x12\r\n" +
	"\tFIELD_ORG\x10\t\x12\x10\n" +
	"\fFIELD_AUTHOR\x10\n" +
	"\x12\x12\n" +
	"\x0eFIELD_ASSIGNEE\x10\v\x12\x13\n" +
	"\x0fFIELD_MILESTONE\x10\f\x12\x0f\n" +
	"\vFIELD_LABEL\x10\r\x12\f\n" +
	"\bFIELD_NO\x10\x0e\x12\f\n" +
	"\bFIELD_IN\x10\x0f\x12\x0e\n" +
	"\n" +
	"FIELD_TEXT\x10\x10*c\n" +
	"\aSortKey\x12\x18\n" +
	"\x14SORT_KEY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SORT_KEY_UPDATED\x10\x01\x12\x12\n" +
	"\x0eSORT_KEY_ACKED\x10\x02\x12\x14\n" +
	"\x10SORT_KEY_CREATED\x10\x03*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x01\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x02B\xb5\x01\n" +
	"\x0fcom.octodeck.v1B\n" +
	"QueryProtoP\x01ZIgithub.com/tallclair/octodeck/backend/internal/api/octodeck/v1;octodeckv1\xa2\x02\x03OXX\xaa\x02\vOctodeck.V1\xca\x02\vOctodeck\\V1\xe2\x02\x17Octodeck\\V1\\GPBMetadata\xea\x02\fOctodeck::V1b\beditionsp\xe8\a"

var file_octodeck_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_octodeck_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_octodeck_v1_query_proto_goTypes = []any{
	(Field)(0),                    // 0: octodeck.v1.Field
	(SortKey)(0),                  // 1: octodeck.v1.SortKey
	(SortOrder)(0),                // 2: octodeck.v1.SortOrder
	(*Expr)(nil),                  // 3: octodeck.v1.Expr
	(*ExprList)(nil),              // 4: octodeck.v1.ExprList
	(*Predicate)(nil),             // 5: octodeck.v1.Predicate
	(*Sort)(nil),                  // 6: octodeck.v1.Sort
	(*Facet)(nil),                 // 7: octodeck.v1.Facet
	(*FacetValue)(nil),            // 8: octodeck.v1.FacetValue
	(*ExprError)(nil),             // 9: octodeck.v1.ExprError
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_octodeck_v1_query_proto_depIdxs = []int32{
	5,  // 0: octodeck.v1.Expr.predicate:type_name -> octodeck.v1.Predicate
	4,  // 1: octodeck.v1.Expr.and:type_name -> octodeck.v1.ExprList
	4,  // 2: octodeck.v1.Expr.or:type_name -> octodeck.v1.ExprList
	3,  // 3: octodeck.v1.Expr.not:type_name -> octodeck.v1.Expr
	3,  // 4: octodeck.v1.ExprList.exprs:type_name -> octodeck.v1.Expr
	0,  // 5: octodeck.v1.Predicate.field:type_name -> octodeck.v1.Field
	1,  // 6: octodeck.v1.Sort.key:type_name -> octodeck.v1.SortKey
	2,  // 7: octodeck.v1.Sort.order:type_name -> octodeck.v1.SortOrder
	0,  // 8: octodeck.v1.Facet.field:type_name -> octodeck.v1.Field
	8,  // 9: octodeck.v1.Facet.values:type_name -> octodeck.v1.FacetValue
	10, // 10: octodeck.v1.FacetValue.latest_activity_at:type_name -> google.protobuf.Timestamp
	0,  // 11: octodeck.v1.ExprError.field:type_name -> octodeck.v1.Field
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_octodeck_v1_query_proto_init() }
func file_octodeck_v1_query_proto_init() {
	if File_octodeck_v1_query_proto != nil {
		return
	}
	file_octodeck_v1_query_proto_msgTypes[0].OneofWrappers = []any{
		(*expr_Predicate)(nil),
		(*expr_And)(nil),
		(*expr_Or)(nil),
		(*expr_Not)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_octodeck_v1_query_proto_rawDesc), len(file_octodeck_v1_query_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_octodeck_v1_query_proto_goTypes,
		DependencyIndexes: file_octodeck_v1_query_proto_depIdxs,
		EnumInfos:         file_octodeck_v1_query_proto_enumTypes,
		MessageInfos:      file_octodeck_v1_query_proto_msgTypes,
	}.Build()
	File_octodeck_v1_query_proto = out.File
	file_octodeck_v1_query_proto_goTypes = nil
	file_octodeck_v1_query_proto_depIdxs = nil
}
