// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: octodeck/v1/resources.proto

package octodeckv1

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemType int32

const (
	ItemType_ITEM_TYPE_UNSPECIFIED ItemType = 0
	ItemType_ITEM_TYPE_ISSUE       ItemType = 1
	ItemType_ITEM_TYPE_PR          ItemType = 2
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ITEM_TYPE_UNSPECIFIED",
		1: "ITEM_TYPE_ISSUE",
		2: "ITEM_TYPE_PR",
	}
	ItemType_value = map[string]int32{
		"ITEM_TYPE_UNSPECIFIED": 0,
		"ITEM_TYPE_ISSUE":       1,
		"ITEM_TYPE_PR":          2,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_octodeck_v1_resources_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_octodeck_v1_resources_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ItemState int32

const (
	ItemState_ITEM_STATE_UNSPECIFIED ItemState = 0
	ItemState_ITEM_STATE_OPEN        ItemState = 1
	ItemState_ITEM_STATE_CLOSED      ItemState = 2
	ItemState_ITEM_STATE_MERGED      ItemState = 3
)

// Enum value maps for ItemState.
var (
	ItemState_name = map[int32]string{
		0: "ITEM_STATE_UNSPECIFIED",
		1: "ITEM_STATE_OPEN",
		2: "ITEM_STATE_CLOSED",
		3: "ITEM_STATE_MERGED",
	}
	ItemState_value = map[string]int32{
		"ITEM_STATE_UNSPECIFIED": 0,
		"ITEM_STATE_OPEN":        1,
		"ITEM_STATE_CLOSED":      2,
		"ITEM_STATE_MERGED":      3,
	}
)

func (x ItemState) Enum() *ItemState {
	p := new(ItemState)
	*p = x
	return p
}

func (x ItemState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemState) Descriptor() protoreflect.EnumDescriptor {
	return file_octodeck_v1_resources_proto_enumTypes[1].Descriptor()
}

func (ItemState) Type() protoreflect.EnumType {
	return &file_octodeck_v1_resources_proto_enumTypes[1]
}

func (x ItemState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type UserType int32

const (
	UserType_USER_TYPE_UNSPECIFIED UserType = 0
	UserType_USER_TYPE_USER        UserType = 1
	UserType_USER_TYPE_BOT         UserType = 2
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "USER_TYPE_UNSPECIFIED",
		1: "USER_TYPE_USER",
		2: "USER_TYPE_BOT",
	}
	UserType_value = map[string]int32{
		"USER_TYPE_UNSPECIFIED": 0,
		"USER_TYPE_USER":        1,
		"USER_TYPE_BOT":         2,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_octodeck_v1_resources_proto_enumTypes[2].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_octodeck_v1_resources_proto_enumTypes[2]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ItemStatus int32

const (
	ItemStatus_ITEM_STATUS_UNSPECIFIED  ItemStatus = 0
	ItemStatus_ITEM_STATUS_NEW          ItemStatus = 1
	ItemStatus_ITEM_STATUS_IDLE         ItemStatus = 2
	ItemStatus_ITEM_STATUS_NEW_ACTIVITY ItemStatus = 3
	ItemStatus_ITEM_STATUS_NEW_CODE     ItemStatus = 4
	ItemStatus_ITEM_STATUS_ACKED        ItemStatus = 5
	ItemStatus_ITEM_STATUS_NOISE        ItemStatus = 6
)

// Enum value maps for ItemStatus.
var (
	ItemStatus_name = map[int32]string{
		0: "ITEM_STATUS_UNSPECIFIED",
		1: "ITEM_STATUS_NEW",
		2: "ITEM_STATUS_IDLE",
		3: "ITEM_STATUS_NEW_ACTIVITY",
		4: "ITEM_STATUS_NEW_CODE",
		5: "ITEM_STATUS_ACKED",
		6: "ITEM_STATUS_NOISE",
	}
	ItemStatus_value = map[string]int32{
		"ITEM_STATUS_UNSPECIFIED":  0,
		"ITEM_STATUS_NEW":          1,
		"ITEM_STATUS_IDLE":         2,
		"ITEM_STATUS_NEW_ACTIVITY": 3,
		"ITEM_STATUS_NEW_CODE":     4,
		"ITEM_STATUS_ACKED":        5,
		"ITEM_STATUS_NOISE":        6,
	}
)

func (x ItemStatus) Enum() *ItemStatus {
	p := new(ItemStatus)
	*p = x
	return p
}

func (x ItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_octodeck_v1_resources_proto_enumTypes[3].Descriptor()
}

func (ItemStatus) Type() protoreflect.EnumType {
	return &file_octodeck_v1_resources_proto_enumTypes[3]
}

func (x ItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CommentNoiseType int32

const (
	CommentNoiseType_COMMENT_NOISE_TYPE_UNSPECIFIED   CommentNoiseType = 0
	CommentNoiseType_COMMENT_NOISE_TYPE_BOT_AUTHOR    CommentNoiseType = 1
	CommentNoiseType_COMMENT_NOISE_TYPE_SLASH_COMMAND CommentNoiseType = 2
)

// Enum value maps for CommentNoiseType.
var (
	CommentNoiseType_name = map[int32]string{
		0: "COMMENT_NOISE_TYPE_UNSPECIFIED",
		1: "COMMENT_NOISE_TYPE_BOT_AUTHOR",
		2: "COMMENT_NOISE_TYPE_SLASH_COMMAND",
	}
	CommentNoiseType_value = map[string]int32{
		"COMMENT_NOISE_TYPE_UNSPECIFIED":   0,
		"COMMENT_NOISE_TYPE_BOT_AUTHOR":    1,
		"COMMENT_NOISE_TYPE_SLASH_COMMAND": 2,
	}
)

func (x CommentNoiseType) Enum() *CommentNoiseType {
	p := new(CommentNoiseType)
	*p = x
	return p
}

func (x CommentNoiseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentNoiseType) Descriptor() protoreflect.EnumDescriptor {
	return file_octodeck_v1_resources_proto_enumTypes[4].Descriptor()
}

func (CommentNoiseType) Type() protoreflect.EnumType {
	return &file_octodeck_v1_resources_proto_enumTypes[4]
}

func (x CommentNoiseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type StateChangeType int32

const (
	StateChangeType_STATE_CHANGE_TYPE_UNSPECIFIED StateChangeType = 0
	StateChangeType_STATE_CHANGE_TYPE_CLOSED      StateChangeType = 1
	StateChangeType_STATE_CHANGE_TYPE_MERGED      StateChangeType = 2
	StateChangeType_STATE_CHANGE_TYPE_REOPENED    StateChangeType = 3
	StateChangeType_STATE_CHANGE_TYPE_ASSIGNED    StateChangeType = 4
)

// Enum value maps for StateChangeType.
var (
	StateChangeType_name = map[int32]string{
		0: "STATE_CHANGE_TYPE_UNSPECIFIED",
		1: "STATE_CHANGE_TYPE_CLOSED",
		2: "STATE_CHANGE_TYPE_MERGED",
		3: "STATE_CHANGE_TYPE_REOPENED",
		4: "STATE_CHANGE_TYPE_ASSIGNED",
	}
	StateChangeType_value = map[string]int32{
		"STATE_CHANGE_TYPE_UNSPECIFIED": 0,
		"STATE_CHANGE_TYPE_CLOSED":      1,
		"STATE_CHANGE_TYPE_MERGED":      2,
		"STATE_CHANGE_TYPE_REOPENED":    3,
		"STATE_CHANGE_TYPE_ASSIGNED":    4,
	}
)

func (x StateChangeType) Enum() *StateChangeType {
	p := new(StateChangeType)
	*p = x
	return p
}

func (x StateChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_octodeck_v1_resources_proto_enumTypes[5].Descriptor()
}

func (StateChangeType) Type() protoreflect.EnumType {
	return &file_octodeck_v1_resources_proto_enumTypes[5]
}

func (x StateChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SubscriptionState int32

const (
	SubscriptionState_SUBSCRIPTION_STATE_UNSPECIFIED  SubscriptionState = 0
	SubscriptionState_SUBSCRIPTION_STATE_SUBSCRIBED   SubscriptionState = 1
	SubscriptionState_SUBSCRIPTION_STATE_UNSUBSCRIBED SubscriptionState = 2
	SubscriptionState_SUBSCRIPTION_STATE_IGNORED      SubscriptionState = 3
)

// Enum value maps for SubscriptionState.
var (
	SubscriptionState_name = map[int32]string{
		0: "SUBSCRIPTION_STATE_UNSPECIFIED",
		1: "SUBSCRIPTION_STATE_SUBSCRIBED",
		2: "SUBSCRIPTION_STATE_UNSUBSCRIBED",
		3: "SUBSCRIPTION_STATE_IGNORED",
	}
	SubscriptionState_value = map[string]int32{
		"SUBSCRIPTION_STATE_UNSPECIFIED":  0,
		"SUBSCRIPTION_STATE_SUBSCRIBED":   1,
		"SUBSCRIPTION_STATE_UNSUBSCRIBED": 2,
		"SUBSCRIPTION_STATE_IGNORED":      3,
	}
)

func (x SubscriptionState) Enum() *SubscriptionState {
	p := new(SubscriptionState)
	*p = x
	return p
}

func (x SubscriptionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionState) Descriptor() protoreflect.EnumDescriptor {
	return file_octodeck_v1_resources_proto_enumTypes[6].Descriptor()
}

func (SubscriptionState) Type() protoreflect.EnumType {
	return &file_octodeck_v1_resources_proto_enumTypes[6]
}

func (x SubscriptionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type User struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_AvatarUrl   *string                `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl"`
	xxx_hidden_Type        UserType               `protobuf:"varint,3,opt,name=type,enum=octodeck.v1.UserType"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_octodeck_v1_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *User) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		if x.xxx_hidden_AvatarUrl != nil {
			return *x.xxx_hidden_AvatarUrl
		}
		return ""
	}
	return ""
}

func (x *User) GetType() UserType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Type
		}
	}
	return UserType_USER_TYPE_UNSPECIFIED
}

func (x *User) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *User) SetAvatarUrl(v string) {
	x.xxx_hidden_AvatarUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *User) SetType(v UserType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *User) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *User) HasAvatarUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *User) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *User) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *User) ClearAvatarUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AvatarUrl = nil
}

func (x *User) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Type = UserType_USER_TYPE_UNSPECIFIED
}

type User_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login     *string
	AvatarUrl *string
	Type      *UserType
}

func (b0 User_builder) Build() *User {
	m0 := &User{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Login = b.Login
	}
	if b.AvatarUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_AvatarUrl = b.AvatarUrl
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Type = *b.Type
	}
	return m0
}

type Comment struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt"`
	xxx_hidden_BodyText    *string                `protobuf:"bytes,2,opt,name=body_text,json=bodyText"`
	xxx_hidden_CommentId   int64                  `protobuf:"varint,3,opt,name=comment_id,json=commentId"`
	xxx_hidden_Author      *User                  `protobuf:"bytes,4,opt,name=author"`
	xxx_hidden_NoiseType   CommentNoiseType       `protobuf:"varint,5,opt,name=noise_type,json=noiseType,enum=octodeck.v1.CommentNoiseType"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_octodeck_v1_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Comment) GetBodyText() string {
	if x != nil {
		if x.xxx_hidden_BodyText != nil {
			return *x.xxx_hidden_BodyText
		}
		return ""
	}
	return ""
}

func (x *Comment) GetCommentId() int64 {
	if x != nil {
		return x.xxx_hidden_CommentId
	}
	return 0
}

func (x *Comment) GetAuthor() *User {
	if x != nil {
		return x.xxx_hidden_Author
	}
	return nil
}

func (x *Comment) GetNoiseType() CommentNoiseType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_NoiseType
		}
	}
	return CommentNoiseType_COMMENT_NOISE_TYPE_UNSPECIFIED
}

func (x *Comment) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Comment) SetBodyText(v string) {
	x.xxx_hidden_BodyText = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Comment) SetCommentId(v int64) {
	x.xxx_hidden_CommentId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Comment) SetAuthor(v *User) {
	x.xxx_hidden_Author = v
}

func (x *Comment) SetNoiseType(v CommentNoiseType) {
	x.xxx_hidden_NoiseType = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Comment) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Comment) HasBodyText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Comment) HasCommentId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Comment) HasAuthor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Author != nil
}

func (x *Comment) HasNoiseType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Comment) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Comment) ClearBodyText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_BodyText = nil
}

func (x *Comment) ClearCommentId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CommentId = 0
}

func (x *Comment) ClearAuthor() {
	x.xxx_hidden_Author = nil
}

func (x *Comment) ClearNoiseType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_NoiseType = CommentNoiseType_COMMENT_NOISE_TYPE_UNSPECIFIED
}

type Comment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CreatedAt *timestamppb.Timestamp
	BodyText  *string
	CommentId *int64
	Author    *User
	NoiseType *CommentNoiseType
}

func (b0 Comment_builder) Build() *Comment {
	m0 := &Comment{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CreatedAt = b.CreatedAt
	if b.BodyText != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_BodyText = b.BodyText
	}
	if b.CommentId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_CommentId = *b.CommentId
	}
	x.xxx_hidden_Author = b.Author
	if b.NoiseType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_NoiseType = *b.NoiseType
	}
	return m0
}

type ReviewComment struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Body        *string                `protobuf:"bytes,2,opt,name=body"`
	xxx_hidden_Path        *string                `protobuf:"bytes,3,opt,name=path"`
	xxx_hidden_Url         *string                `protobuf:"bytes,4,opt,name=url"`
	xxx_hidden_Author      *User                  `protobuf:"bytes,5,opt,name=author"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt"`
	xxx_hidden_ReplyToId   *string                `protobuf:"bytes,7,opt,name=reply_to_id,json=replyToId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReviewComment) Reset() {
	*x = ReviewComment{}
	mi := &file_octodeck_v1_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewComment) ProtoMessage() {}

func (x *ReviewComment) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReviewComment) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ReviewComment) GetBody() string {
	if x != nil {
		if x.xxx_hidden_Body != nil {
			return *x.xxx_hidden_Body
		}
		return ""
	}
	return ""
}

func (x *ReviewComment) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *ReviewComment) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *ReviewComment) GetAuthor() *User {
	if x != nil {
		return x.xxx_hidden_Author
	}
	return nil
}

func (x *ReviewComment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *ReviewComment) GetReplyToId() string {
	if x != nil {
		if x.xxx_hidden_ReplyToId != nil {
			return *x.xxx_hidden_ReplyToId
		}
		return ""
	}
	return ""
}

func (x *ReviewComment) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *ReviewComment) SetBody(v string) {
	x.xxx_hidden_Body = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *ReviewComment) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *ReviewComment) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *ReviewComment) SetAuthor(v *User) {
	x.xxx_hidden_Author = v
}

func (x *ReviewComment) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *ReviewComment) SetReplyToId(v string) {
	x.xxx_hidden_ReplyToId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *ReviewComment) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReviewComment) HasBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReviewComment) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ReviewComment) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ReviewComment) HasAuthor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Author != nil
}

func (x *ReviewComment) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *ReviewComment) HasReplyToId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ReviewComment) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *ReviewComment) ClearBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Body = nil
}

func (x *ReviewComment) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Path = nil
}

func (x *ReviewComment) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Url = nil
}

func (x *ReviewComment) ClearAuthor() {
	x.xxx_hidden_Author = nil
}

func (x *ReviewComment) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *ReviewComment) ClearReplyToId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ReplyToId = nil
}

type ReviewComment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	Body      *string
	Path      *string
	Url       *string
	Author    *User
	CreatedAt *timestamppb.Timestamp
	ReplyToId *string
}

func (b0 ReviewComment_builder) Build() *ReviewComment {
	m0 := &ReviewComment{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = b.Id
	}
	if b.Body != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Body = b.Body
	}
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Path = b.Path
	}
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Url = b.Url
	}
	x.xxx_hidden_Author = b.Author
	x.xxx_hidden_CreatedAt = b.CreatedAt
	if b.ReplyToId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_ReplyToId = b.ReplyToId
	}
	return m0
}

type Review struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SubmittedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=submitted_at,json=submittedAt"`
	xxx_hidden_State           *string                `protobuf:"bytes,2,opt,name=state"`
	xxx_hidden_Author          *User                  `protobuf:"bytes,3,opt,name=author"`
	xxx_hidden_Body            *string                `protobuf:"bytes,4,opt,name=body"`
	xxx_hidden_CommentCount    int32                  `protobuf:"varint,5,opt,name=comment_count,json=commentCount"`
	xxx_hidden_Url             *string                `protobuf:"bytes,6,opt,name=url"`
	xxx_hidden_NewThreadsCount int32                  `protobuf:"varint,7,opt,name=new_threads_count,json=newThreadsCount"`
	xxx_hidden_ReplyCount      int32                  `protobuf:"varint,8,opt,name=reply_count,json=replyCount"`
	xxx_hidden_Comments        *[]*ReviewComment      `protobuf:"bytes,9,rep,name=comments"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_octodeck_v1_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Review) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_SubmittedAt
	}
	return nil
}

func (x *Review) GetState() string {
	if x != nil {
		if x.xxx_hidden_State != nil {
			return *x.xxx_hidden_State
		}
		return ""
	}
	return ""
}

func (x *Review) GetAuthor() *User {
	if x != nil {
		return x.xxx_hidden_Author
	}
	return nil
}

func (x *Review) GetBody() string {
	if x != nil {
		if x.xxx_hidden_Body != nil {
			return *x.xxx_hidden_Body
		}
		return ""
	}
	return ""
}

func (x *Review) GetCommentCount() int32 {
	if x != nil {
		return x.xxx_hidden_CommentCount
	}
	return 0
}

func (x *Review) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *Review) GetNewThreadsCount() int32 {
	if x != nil {
		return x.xxx_hidden_NewThreadsCount
	}
	return 0
}

func (x *Review) GetReplyCount() int32 {
	if x != nil {
		return x.xxx_hidden_ReplyCount
	}
	return 0
}

func (x *Review) GetComments() []*ReviewComment {
	if x != nil {
		if x.xxx_hidden_Comments != nil {
			return *x.xxx_hidden_Comments
		}
	}
	return nil
}

func (x *Review) SetSubmittedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_SubmittedAt = v
}

func (x *Review) SetState(v string) {
	x.xxx_hidden_State = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *Review) SetAuthor(v *User) {
	x.xxx_hidden_Author = v
}

func (x *Review) SetBody(v string) {
	x.xxx_hidden_Body = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *Review) SetCommentCount(v int32) {
	x.xxx_hidden_CommentCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *Review) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *Review) SetNewThreadsCount(v int32) {
	x.xxx_hidden_NewThreadsCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *Review) SetReplyCount(v int32) {
	x.xxx_hidden_ReplyCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *Review) SetComments(v []*ReviewComment) {
	x.xxx_hidden_Comments = &v
}

func (x *Review) HasSubmittedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SubmittedAt != nil
}

func (x *Review) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Review) HasAuthor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Author != nil
}

func (x *Review) HasBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Review) HasCommentCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Review) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Review) HasNewThreadsCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Review) HasReplyCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Review) ClearSubmittedAt() {
	x.xxx_hidden_SubmittedAt = nil
}

func (x *Review) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_State = nil
}

func (x *Review) ClearAuthor() {
	x.xxx_hidden_Author = nil
}

func (x *Review) ClearBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Body = nil
}

func (x *Review) ClearCommentCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_CommentCount = 0
}

func (x *Review) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Url = nil
}

func (x *Review) ClearNewThreadsCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_NewThreadsCount = 0
}

func (x *Review) ClearReplyCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_ReplyCount = 0
}

type Review_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SubmittedAt     *timestamppb.Timestamp
	State           *string
	Author          *User
	Body            *string
	CommentCount    *int32
	Url             *string
	NewThreadsCount *int32
	ReplyCount      *int32
	Comments        []*ReviewComment
}

func (b0 Review_builder) Build() *Review {
	m0 := &Review{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SubmittedAt = b.SubmittedAt
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_State = b.State
	}
	x.xxx_hidden_Author = b.Author
	if b.Body != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Body = b.Body
	}
	if b.CommentCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_CommentCount = *b.CommentCount
	}
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Url = b.Url
	}
	if b.NewThreadsCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_NewThreadsCount = *b.NewThreadsCount
	}
	if b.ReplyCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_ReplyCount = *b.ReplyCount
	}
	x.xxx_hidden_Comments = &b.Comments
	return m0
}

type Commit struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CommittedDate *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=committed_date,json=committedDate"`
	xxx_hidden_AuthorLogin   *string                `protobuf:"bytes,2,opt,name=author_login,json=authorLogin"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_octodeck_v1_resources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_resources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Commit) GetCommittedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CommittedDate
	}
	return nil
}

func (x *Commit) GetAuthorLogin() string {
	if x != nil {
		if x.xxx_hidden_AuthorLogin != nil {
			return *x.xxx_hidden_AuthorLogin
		}
		return ""
	}
	return ""
}

func (x *Commit) SetCommittedDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_CommittedDate = v
}

func (x *Commit) SetAuthorLogin(v string) {
	x.xxx_hidden_AuthorLogin = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Commit) HasCommittedDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CommittedDate != nil
}

func (x *Commit) HasAuthorLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Commit) ClearCommittedDate() {
	x.xxx_hidden_CommittedDate = nil
}

func (x *Commit) ClearAuthorLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AuthorLogin = nil
}

type Commit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CommittedDate *timestamppb.Timestamp
	AuthorLogin   *string
}

func (b0 Commit_builder) Build() *Commit {
	m0 := &Commit{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CommittedDate = b.CommittedDate
	if b.AuthorLogin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_AuthorLogin = b.AuthorLogin
	}
	return m0
}

type Milestone struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title       *string                `protobuf:"bytes,1,opt,name=title"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Milestone) Reset() {
	*x = Milestone{}
	mi := &file_octodeck_v1_resources_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Milestone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Milestone) ProtoMessage() {}

func (x *Milestone) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_resources_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Milestone) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *Milestone) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Milestone) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Milestone) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Title = nil
}

type Milestone_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title *string
}

func (b0 Milestone_builder) Build() *Milestone {
	m0 := &Milestone{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Title = b.Title
	}
	return m0
}

type StateEvent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        StateChangeType        `protobuf:"varint,1,opt,name=type,enum=octodeck.v1.StateChangeType"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt"`
	xxx_hidden_Actor       *User                  `protobuf:"bytes,3,opt,name=actor"`
	xxx_hidden_Url         *string                `protobuf:"bytes,4,opt,name=url"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StateEvent) Reset() {
	*x = StateEvent{}
	mi := &file_octodeck_v1_resources_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateEvent) ProtoMessage() {}

func (x *StateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_resources_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StateEvent) GetType() StateChangeType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return StateChangeType_STATE_CHANGE_TYPE_UNSPECIFIED
}

func (x *StateEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *StateEvent) GetActor() *User {
	if x != nil {
		return x.xxx_hidden_Actor
	}
	return nil
}

func (x *StateEvent) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *StateEvent) SetType(v StateChangeType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *StateEvent) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *StateEvent) SetActor(v *User) {
	x.xxx_hidden_Actor = v
}

func (x *StateEvent) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *StateEvent) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StateEvent) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *StateEvent) HasActor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Actor != nil
}

func (x *StateEvent) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *StateEvent) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = StateChangeType_STATE_CHANGE_TYPE_UNSPECIFIED
}

func (x *StateEvent) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *StateEvent) ClearActor() {
	x.xxx_hidden_Actor = nil
}

func (x *StateEvent) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Url = nil
}

type StateEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type      *StateChangeType
	CreatedAt *timestamppb.Timestamp
	Actor     *User
	Url       *string
}

func (b0 StateEvent_builder) Build() *StateEvent {
	m0 := &StateEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Type = *b.Type
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_Actor = b.Actor
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Url = b.Url
	}
	return m0
}

type Label struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Color       *string                `protobuf:"bytes,2,opt,name=color"`
	xxx_hidden_Description *string                `protobuf:"bytes,3,opt,name=description"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_octodeck_v1_resources_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_resources_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Label) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Label) GetColor() string {
	if x != nil {
		if x.xxx_hidden_Color != nil {
			return *x.xxx_hidden_Color
		}
		return ""
	}
	return ""
}

func (x *Label) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *Label) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Label) SetColor(v string) {
	x.xxx_hidden_Color = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Label) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Label) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Label) HasColor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Label) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Label) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Label) ClearColor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Color = nil
}

func (x *Label) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

type Label_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        *string
	Color       *string
	Description *string
}

func (b0 Label_builder) Build() *Label {
	m0 := &Label{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Name = b.Name
	}
	if b.Color != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Color = b.Color
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Description = b.Description
	}
	return m0
}

type ItemLocalState struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ComputedStatus ItemStatus             `protobuf:"varint,1,opt,name=computed_status,json=computedStatus,enum=octodeck.v1.ItemStatus"`
	xxx_hidden_LastViewedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_viewed_at,json=lastViewedAt"`
	xxx_hidden_AckedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=acked_at,json=ackedAt"`
	xxx_hidden_PrivateNotes   *string                `protobuf:"bytes,5,opt,name=private_notes,json=privateNotes"`
	xxx_hidden_Starred        bool                   `protobuf:"varint,6,opt,name=starred"`
	xxx_hidden_SyncError      *string                `protobuf:"bytes,7,opt,name=sync_error,json=syncError"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ItemLocalState) Reset() {
	*x = ItemLocalState{}
	mi := &file_octodeck_v1_resources_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemLocalState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemLocalState) ProtoMessage() {}

func (x *ItemLocalState) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_resources_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ItemLocalState) GetComputedStatus() ItemStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_ComputedStatus
		}
	}
	return ItemStatus_ITEM_STATUS_UNSPECIFIED
}

func (x *ItemLocalState) GetLastViewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastViewedAt
	}
	return nil
}

func (x *ItemLocalState) GetAckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_AckedAt
	}
	return nil
}

func (x *ItemLocalState) GetPrivateNotes() string {
	if x != nil {
		if x.xxx_hidden_PrivateNotes != nil {
			return *x.xxx_hidden_PrivateNotes
		}
		return ""
	}
	return ""
}

func (x *ItemLocalState) GetStarred() bool {
	if x != nil {
		return x.xxx_hidden_Starred
	}
	return false
}

func (x *ItemLocalState) GetSyncError() string {
	if x != nil {
		if x.xxx_hidden_SyncError != nil {
			return *x.xxx_hidden_SyncError
		}
		return ""
	}
	return ""
}

func (x *ItemLocalState) SetComputedStatus(v ItemStatus) {
	x.xxx_hidden_ComputedStatus = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *ItemLocalState) SetLastViewedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastViewedAt = v
}

func (x *ItemLocalState) SetAckedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_AckedAt = v
}

func (x *ItemLocalState) SetPrivateNotes(v string) {
	x.xxx_hidden_PrivateNotes = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *ItemLocalState) SetStarred(v bool) {
	x.xxx_hidden_Starred = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *ItemLocalState) SetSyncError(v string) {
	x.xxx_hidden_SyncError = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *ItemLocalState) HasComputedStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ItemLocalState) HasLastViewedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastViewedAt != nil
}

func (x *ItemLocalState) HasAckedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AckedAt != nil
}

func (x *ItemLocalState) HasPrivateNotes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ItemLocalState) HasStarred() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ItemLocalState) HasSyncError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ItemLocalState) ClearComputedStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ComputedStatus = ItemStatus_ITEM_STATUS_UNSPECIFIED
}

func (x *ItemLocalState) ClearLastViewedAt() {
	x.xxx_hidden_LastViewedAt = nil
}

func (x *ItemLocalState) ClearAckedAt() {
	x.xxx_hidden_AckedAt = nil
}

func (x *ItemLocalState) ClearPrivateNotes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_PrivateNotes = nil
}

func (x *ItemLocalState) ClearStarred() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Starred = false
}

func (x *ItemLocalState) ClearSyncError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_SyncError = nil
}

type ItemLocalState_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ComputedStatus *ItemStatus
	LastViewedAt   *timestamppb.Timestamp
	AckedAt        *timestamppb.Timestamp
	PrivateNotes   *string
	Starred        *bool
	SyncError      *string
}

func (b0 ItemLocalState_builder) Build() *ItemLocalState {
	m0 := &ItemLocalState{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ComputedStatus != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_ComputedStatus = *b.ComputedStatus
	}
	x.xxx_hidden_LastViewedAt = b.LastViewedAt
	x.xxx_hidden_AckedAt = b.AckedAt
	if b.PrivateNotes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_PrivateNotes = b.PrivateNotes
	}
	if b.Starred != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Starred = *b.Starred
	}
	if b.SyncError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_SyncError = b.SyncError
	}
	return m0
}

type Item struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                 *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Repo               *string                `protobuf:"bytes,2,opt,name=repo"`
	xxx_hidden_Number             int32                  `protobuf:"varint,3,opt,name=number"`
	xxx_hidden_Type               ItemType               `protobuf:"varint,4,opt,name=type,enum=octodeck.v1.ItemType"`
	xxx_hidden_Title              *string                `protobuf:"bytes,5,opt,name=title"`
	xxx_hidden_State              ItemState              `protobuf:"varint,6,opt,name=state,enum=octodeck.v1.ItemState"`
	xxx_hidden_UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_LastSyncedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_synced_at,json=lastSyncedAt"`
	xxx_hidden_Url                *string                `protobuf:"bytes,9,opt,name=url"`
	xxx_hidden_Author             *User                  `protobuf:"bytes,10,opt,name=author"`
	xxx_hidden_Commits            *[]*Commit             `protobuf:"bytes,11,rep,name=commits"`
	xxx_hidden_Comments           *[]*Comment            `protobuf:"bytes,12,rep,name=comments"`
	xxx_hidden_Reviews            *[]*Review             `protobuf:"bytes,13,rep,name=reviews"`
	xxx_hidden_Assignees          *[]*User               `protobuf:"bytes,14,rep,name=assignees"`
	xxx_hidden_Local              *ItemLocalState        `protobuf:"bytes,15,opt,name=local"`
	xxx_hidden_Body               *string                `protobuf:"bytes,16,opt,name=body"`
	xxx_hidden_CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt"`
	xxx_hidden_Milestone          *Milestone             `protobuf:"bytes,18,opt,name=milestone"`
	xxx_hidden_Labels             *[]*Label              `protobuf:"bytes,19,rep,name=labels"`
	xxx_hidden_StateEvents        *[]*StateEvent         `protobuf:"bytes,20,rep,name=state_events,json=stateEvents"`
	xxx_hidden_ViewerSubscription SubscriptionState      `protobuf:"varint,21,opt,name=viewer_subscription,json=viewerSubscription,enum=octodeck.v1.SubscriptionState"`
	xxx_hidden_IsDraft            bool                   `protobuf:"varint,22,opt,name=is_draft,json=isDraft"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_octodeck_v1_resources_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_resources_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Item) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Item) GetRepo() string {
	if x != nil {
		if x.xxx_hidden_Repo != nil {
			return *x.xxx_hidden_Repo
		}
		return ""
	}
	return ""
}

func (x *Item) GetNumber() int32 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *Item) GetType() ItemType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_Type
		}
	}
	return ItemType_ITEM_TYPE_UNSPECIFIED
}

func (x *Item) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *Item) GetState() ItemState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_State
		}
	}
	return ItemState_ITEM_STATE_UNSPECIFIED
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Item) GetLastSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastSyncedAt
	}
	return nil
}

func (x *Item) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *Item) GetAuthor() *User {
	if x != nil {
		return x.xxx_hidden_Author
	}
	return nil
}

func (x *Item) GetCommits() []*Commit {
	if x != nil {
		if x.xxx_hidden_Commits != nil {
			return *x.xxx_hidden_Commits
		}
	}
	return nil
}

func (x *Item) GetComments() []*Comment {
	if x != nil {
		if x.xxx_hidden_Comments != nil {
			return *x.xxx_hidden_Comments
		}
	}
	return nil
}

func (x *Item) GetReviews() []*Review {
	if x != nil {
		if x.xxx_hidden_Reviews != nil {
			return *x.xxx_hidden_Reviews
		}
	}
	return nil
}

func (x *Item) GetAssignees() []*User {
	if x != nil {
		if x.xxx_hidden_Assignees != nil {
			return *x.xxx_hidden_Assignees
		}
	}
	return nil
}

func (x *Item) GetLocal() *ItemLocalState {
	if x != nil {
		return x.xxx_hidden_Local
	}
	return nil
}

func (x *Item) GetBody() string {
	if x != nil {
		if x.xxx_hidden_Body != nil {
			return *x.xxx_hidden_Body
		}
		return ""
	}
	return ""
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Item) GetMilestone() *Milestone {
	if x != nil {
		return x.xxx_hidden_Milestone
	}
	return nil
}

func (x *Item) GetLabels() []*Label {
	if x != nil {
		if x.xxx_hidden_Labels != nil {
			return *x.xxx_hidden_Labels
		}
	}
	return nil
}

func (x *Item) GetStateEvents() []*StateEvent {
	if x != nil {
		if x.xxx_hidden_StateEvents != nil {
			return *x.xxx_hidden_StateEvents
		}
	}
	return nil
}

func (x *Item) GetViewerSubscription() SubscriptionState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 20) {
			return x.xxx_hidden_ViewerSubscription
		}
	}
	return SubscriptionState_SUBSCRIPTION_STATE_UNSPECIFIED
}

func (x *Item) GetIsDraft() bool {
	if x != nil {
		return x.xxx_hidden_IsDraft
	}
	return false
}

func (x *Item) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 22)
}

func (x *Item) SetRepo(v string) {
	x.xxx_hidden_Repo = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 22)
}

func (x *Item) SetNumber(v int32) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 22)
}

func (x *Item) SetType(v ItemType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 22)
}

func (x *Item) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 22)
}

func (x *Item) SetState(v ItemState) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 22)
}

func (x *Item) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Item) SetLastSyncedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastSyncedAt = v
}

func (x *Item) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 22)
}

func (x *Item) SetAuthor(v *User) {
	x.xxx_hidden_Author = v
}

func (x *Item) SetCommits(v []*Commit) {
	x.xxx_hidden_Commits = &v
}

func (x *Item) SetComments(v []*Comment) {
	x.xxx_hidden_Comments = &v
}

func (x *Item) SetReviews(v []*Review) {
	x.xxx_hidden_Reviews = &v
}

func (x *Item) SetAssignees(v []*User) {
	x.xxx_hidden_Assignees = &v
}

func (x *Item) SetLocal(v *ItemLocalState) {
	x.xxx_hidden_Local = v
}

func (x *Item) SetBody(v string) {
	x.xxx_hidden_Body = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 22)
}

func (x *Item) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Item) SetMilestone(v *Milestone) {
	x.xxx_hidden_Milestone = v
}

func (x *Item) SetLabels(v []*Label) {
	x.xxx_hidden_Labels = &v
}

func (x *Item) SetStateEvents(v []*StateEvent) {
	x.xxx_hidden_StateEvents = &v
}

func (x *Item) SetViewerSubscription(v SubscriptionState) {
	x.xxx_hidden_ViewerSubscription = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 20, 22)
}

func (x *Item) SetIsDraft(v bool) {
	x.xxx_hidden_IsDraft = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 21, 22)
}

func (x *Item) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Item) HasRepo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Item) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Item) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Item) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Item) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Item) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Item) HasLastSyncedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastSyncedAt != nil
}

func (x *Item) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *Item) HasAuthor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Author != nil
}

func (x *Item) HasLocal() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Local != nil
}

func (x *Item) HasBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *Item) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Item) HasMilestone() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Milestone != nil
}

func (x *Item) HasViewerSubscription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 20)
}

func (x *Item) HasIsDraft() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 21)
}

func (x *Item) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Item) ClearRepo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Repo = nil
}

func (x *Item) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Number = 0
}

func (x *Item) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Type = ItemType_ITEM_TYPE_UNSPECIFIED
}

func (x *Item) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Title = nil
}

func (x *Item) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_State = ItemState_ITEM_STATE_UNSPECIFIED
}

func (x *Item) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *Item) ClearLastSyncedAt() {
	x.xxx_hidden_LastSyncedAt = nil
}

func (x *Item) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Url = nil
}

func (x *Item) ClearAuthor() {
	x.xxx_hidden_Author = nil
}

func (x *Item) ClearLocal() {
	x.xxx_hidden_Local = nil
}

func (x *Item) ClearBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_Body = nil
}

func (x *Item) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Item) ClearMilestone() {
	x.xxx_hidden_Milestone = nil
}

func (x *Item) ClearViewerSubscription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 20)
	x.xxx_hidden_ViewerSubscription = SubscriptionState_SUBSCRIPTION_STATE_UNSPECIFIED
}

func (x *Item) ClearIsDraft() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 21)
	x.xxx_hidden_IsDraft = false
}

type Item_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                 *string
	Repo               *string
	Number             *int32
	Type               *ItemType
	Title              *string
	State              *ItemState
	UpdatedAt          *timestamppb.Timestamp
	LastSyncedAt       *timestamppb.Timestamp
	Url                *string
	Author             *User
	Commits            []*Commit
	Comments           []*Comment
	Reviews            []*Review
	Assignees          []*User
	Local              *ItemLocalState
	Body               *string
	CreatedAt          *timestamppb.Timestamp
	Milestone          *Milestone
	Labels             []*Label
	StateEvents        []*StateEvent
	ViewerSubscription *SubscriptionState
	IsDraft            *bool
}

func (b0 Item_builder) Build() *Item {
	m0 := &Item{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 22)
		x.xxx_hidden_Id = b.Id
	}
	if b.Repo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 22)
		x.xxx_hidden_Repo = b.Repo
	}
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 22)
		x.xxx_hidden_Number = *b.Number
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 22)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 22)
		x.xxx_hidden_Title = b.Title
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 22)
		x.xxx_hidden_State = *b.State
	}
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_LastSyncedAt = b.LastSyncedAt
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 22)
		x.xxx_hidden_Url = b.Url
	}
	x.xxx_hidden_Author = b.Author
	x.xxx_hidden_Commits = &b.Commits
	x.xxx_hidden_Comments = &b.Comments
	x.xxx_hidden_Reviews = &b.Reviews
	x.xxx_hidden_Assignees = &b.Assignees
	x.xxx_hidden_Local = b.Local
	if b.Body != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 22)
		x.xxx_hidden_Body = b.Body
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_Milestone = b.Milestone
	x.xxx_hidden_Labels = &b.Labels
	x.xxx_hidden_StateEvents = &b.StateEvents
	if b.ViewerSubscription != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 20, 22)
		x.xxx_hidden_ViewerSubscription = *b.ViewerSubscription
	}
	if b.IsDraft != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 21, 22)
		x.xxx_hidden_IsDraft = *b.IsDraft
	}
	return m0
}

type SyncTrace struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                 *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_TraceType          *string                `protobuf:"bytes,2,opt,name=trace_type,json=traceType"`
	xxx_hidden_TriggerSource      *string                `protobuf:"bytes,3,opt,name=trigger_source,json=triggerSource"`
	xxx_hidden_QueryString        *string                `protobuf:"bytes,4,opt,name=query_string,json=queryString"`
	xxx_hidden_ReposEvaluated     []string               `protobuf:"bytes,5,rep,name=repos_evaluated,json=reposEvaluated"`
	xxx_hidden_SinceTimestamp     *string                `protobuf:"bytes,6,opt,name=since_timestamp,json=sinceTimestamp"`
	xxx_hidden_DurationMs         int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs"`
	xxx_hidden_PagesCount         int64                  `protobuf:"varint,8,opt,name=pages_count,json=pagesCount"`
	xxx_hidden_ItemsFetched       int64                  `protobuf:"varint,9,opt,name=items_fetched,json=itemsFetched"`
	xxx_hidden_ItemsPersisted     int64                  `protobuf:"varint,10,opt,name=items_persisted,json=itemsPersisted"`
	xxx_hidden_RateLimitRemaining int32                  `protobuf:"varint,11,opt,name=rate_limit_remaining,json=rateLimitRemaining"`
	xxx_hidden_ErrorMessage       *string                `protobuf:"bytes,12,opt,name=error_message,json=errorMessage"`
	xxx_hidden_RawPayload         *string                `protobuf:"bytes,13,opt,name=raw_payload,json=rawPayload"`
	xxx_hidden_CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SyncTrace) Reset() {
	*x = SyncTrace{}
	mi := &file_octodeck_v1_resources_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTrace) ProtoMessage() {}

func (x *SyncTrace) ProtoReflect() protoreflect.Message {
	mi := &file_octodeck_v1_resources_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncTrace) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *SyncTrace) GetTraceType() string {
	if x != nil {
		if x.xxx_hidden_TraceType != nil {
			return *x.xxx_hidden_TraceType
		}
		return ""
	}
	return ""
}

func (x *SyncTrace) GetTriggerSource() string {
	if x != nil {
		if x.xxx_hidden_TriggerSource != nil {
			return *x.xxx_hidden_TriggerSource
		}
		return ""
	}
	return ""
}

func (x *SyncTrace) GetQueryString() string {
	if x != nil {
		if x.xxx_hidden_QueryString != nil {
			return *x.xxx_hidden_QueryString
		}
		return ""
	}
	return ""
}

func (x *SyncTrace) GetReposEvaluated() []string {
	if x != nil {
		return x.xxx_hidden_ReposEvaluated
	}
	return nil
}

func (x *SyncTrace) GetSinceTimestamp() string {
	if x != nil {
		if x.xxx_hidden_SinceTimestamp != nil {
			return *x.xxx_hidden_SinceTimestamp
		}
		return ""
	}
	return ""
}

func (x *SyncTrace) GetDurationMs() int64 {
	if x != nil {
		return x.xxx_hidden_DurationMs
	}
	return 0
}

func (x *SyncTrace) GetPagesCount() int64 {
	if x != nil {
		return x.xxx_hidden_PagesCount
	}
	return 0
}

func (x *SyncTrace) GetItemsFetched() int64 {
	if x != nil {
		return x.xxx_hidden_ItemsFetched
	}
	return 0
}

func (x *SyncTrace) GetItemsPersisted() int64 {
	if x != nil {
		return x.xxx_hidden_ItemsPersisted
	}
	return 0
}

func (x *SyncTrace) GetRateLimitRemaining() int32 {
	if x != nil {
		return x.xxx_hidden_RateLimitRemaining
	}
	return 0
}

func (x *SyncTrace) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *SyncTrace) GetRawPayload() string {
	if x != nil {
		if x.xxx_hidden_RawPayload != nil {
			return *x.xxx_hidden_RawPayload
		}
		return ""
	}
	return ""
}

func (x *SyncTrace) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *SyncTrace) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 14)
}

func (x *SyncTrace) SetTraceType(v string) {
	x.xxx_hidden_TraceType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 14)
}

func (x *SyncTrace) SetTriggerSource(v string) {
	x.xxx_hidden_TriggerSource = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 14)
}

func (x *SyncTrace) SetQueryString(v string) {
	x.xxx_hidden_QueryString = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 14)
}

func (x *SyncTrace) SetReposEvaluated(v []string) {
	x.xxx_hidden_ReposEvaluated = v
}

func (x *SyncTrace) SetSinceTimestamp(v string) {
	x.xxx_hidden_SinceTimestamp = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 14)
}

func (x *SyncTrace) SetDurationMs(v int64) {
	x.xxx_hidden_DurationMs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 14)
}

func (x *SyncTrace) SetPagesCount(v int64) {
	x.xxx_hidden_PagesCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 14)
}

func (x *SyncTrace) SetItemsFetched(v int64) {
	x.xxx_hidden_ItemsFetched = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 14)
}

func (x *SyncTrace) SetItemsPersisted(v int64) {
	x.xxx_hidden_ItemsPersisted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 14)
}

func (x *SyncTrace) SetRateLimitRemaining(v int32) {
	x.xxx_hidden_RateLimitRemaining = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 14)
}

func (x *SyncTrace) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 14)
}

func (x *SyncTrace) SetRawPayload(v string) {
	x.xxx_hidden_RawPayload = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 14)
}

func (x *SyncTrace) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *SyncTrace) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SyncTrace) HasTraceType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SyncTrace) HasTriggerSource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SyncTrace) HasQueryString() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SyncTrace) HasSinceTimestamp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *SyncTrace) HasDurationMs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *SyncTrace) HasPagesCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *SyncTrace) HasItemsFetched() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *SyncTrace) HasItemsPersisted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *SyncTrace) HasRateLimitRemaining() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *SyncTrace) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *SyncTrace) HasRawPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *SyncTrace) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *SyncTrace) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *SyncTrace) ClearTraceType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TraceType = nil
}

func (x *SyncTrace) ClearTriggerSource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_TriggerSource = nil
}

func (x *SyncTrace) ClearQueryString() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_QueryString = nil
}

func (x *SyncTrace) ClearSinceTimestamp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_SinceTimestamp = nil
}

func (x *SyncTrace) ClearDurationMs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DurationMs = 0
}

func (x *SyncTrace) ClearPagesCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_PagesCount = 0
}

func (x *SyncTrace) ClearItemsFetched() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_ItemsFetched = 0
}

func (x *SyncTrace) ClearItemsPersisted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_ItemsPersisted = 0
}

func (x *SyncTrace) ClearRateLimitRemaining() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_RateLimitRemaining = 0
}

func (x *SyncTrace) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_ErrorMessage = nil
}

func (x *SyncTrace) ClearRawPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_RawPayload = nil
}

func (x *SyncTrace) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type SyncTrace_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                 *string
	TraceType          *string
	TriggerSource      *string
	QueryString        *string
	ReposEvaluated     []string
	SinceTimestamp     *string
	DurationMs         *int64
	PagesCount         *int64
	ItemsFetched       *int64
	ItemsPersisted     *int64
	RateLimitRemaining *int32
	ErrorMessage       *string
	RawPayload         *string
	CreatedAt          *timestamppb.Timestamp
}

func (b0 SyncTrace_builder) Build() *SyncTrace {
	m0 := &SyncTrace{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 14)
		x.xxx_hidden_Id = b.Id
	}
	if b.TraceType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 14)
		x.xxx_hidden_TraceType = b.TraceType
	}
	if b.TriggerSource != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 14)
		x.xxx_hidden_TriggerSource = b.TriggerSource
	}
	if b.QueryString != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 14)
		x.xxx_hidden_QueryString = b.QueryString
	}
	x.xxx_hidden_ReposEvaluated = b.ReposEvaluated
	if b.SinceTimestamp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 14)
		x.xxx_hidden_SinceTimestamp = b.SinceTimestamp
	}
	if b.DurationMs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 14)
		x.xxx_hidden_DurationMs = *b.DurationMs
	}
	if b.PagesCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 14)
		x.xxx_hidden_PagesCount = *b.PagesCount
	}
	if b.ItemsFetched != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 14)
		x.xxx_hidden_ItemsFetched = *b.ItemsFetched
	}
	if b.ItemsPersisted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 14)
		x.xxx_hidden_ItemsPersisted = *b.ItemsPersisted
	}
	if b.RateLimitRemaining != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 14)
		x.xxx_hidden_RateLimitRemaining = *b.RateLimitRemaining
	}
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 14)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	if b.RawPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 14)
		x.xxx_hidden_RawPayload = b.RawPayload
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	return m0
}

var File_octodeck_v1_resources_proto protoreflect.FileDescriptor

const file_octodeck_v1_resources_proto_rawDesc = "" +
	"\n" +
	"\x1boctodeck/v1/resources.proto\x12\voctodeck.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n" +
	"\x04User\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tR\tavatarUrl\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.octodeck.v1.UserTypeR\x04type\"\xe9\x01\n" +
	"\aComment\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tbody_text\x18\x02 \x01(\tR\bbodyText\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x03 \x01(\x03R\tcommentId\x12)\n" +
	"\x06author\x18\x04 \x01(\v2\x11.octodeck.v1.UserR\x06author\x12<\n" +
	"\n" +
	"noise_type\x18\x05 \x01(\x0e2\x1d.octodeck.v1.CommentNoiseTypeR\tnoiseType\"\xdf\x01\n" +
	"\rReviewComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12)\n" +
	"\x06author\x18\x05 \x01(\v2\x11.octodeck.v1.UserR\x06author\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1e\n" +
	"\vreply_to_id\x18\a \x01(\tR\treplyToId\"\xd8\x02\n" +
	"\x06Review\x12=\n" +
	"\fsubmitted_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12)\n" +
	"\x06author\x18\x03 \x01(\v2\x11.octodeck.v1.UserR\x06author\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12#\n" +
	"\rcomment_count\x18\x05 \x01(\x05R\fcommentCount\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12*\n" +
	"\x11new_threads_count\x18\a \x01(\x05R\x0fnewThreadsCount\x12\x1f\n" +
	"\vreply_count\x18\b \x01(\x05R\n" +
	"replyCount\x126\n" +
	"\bcomments\x18\t \x03(\v2\x1a.octodeck.v1.ReviewCommentR\bcomments\"n\n" +
	"\x06Commit\x12A\n" +
	"\x0ecommitted_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\rcommittedDate\x12!\n" +
	"\fauthor_login\x18\x02 \x01(\tR\vauthorLogin\"!\n" +
	"\tMilestone\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"\xb4\x01\n" +
	"\n" +
	"StateEvent\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.octodeck.v1.StateChangeTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12'\n" +
	"\x05actor\x18\x03 \x01(\v2\x11.octodeck.v1.UserR\x05actor\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"S\n" +
	"\x05Label\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xaf\x02\n" +
	"\x0eItemLocalState\x12@\n" +
	"\x0fcomputed_status\x18\x01 \x01(\x0e2\x17.octodeck.v1.ItemStatusR\x0ecomputedStatus\x12@\n" +
	"\x0elast_viewed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\flastViewedAt\x125\n" +
	"\backed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aackedAt\x12#\n" +
	"\rprivate_notes\x18\x05 \x01(\tR\fprivateNotes\x12\x18\n" +
	"\astarred\x18\x06 \x01(\bR\astarred\x12\x1d\n" +
	"\n" +
	"sync_error\x18\a \x01(\tR\tsyncErrorJ\x04\b\x04\x10\x05\"\xb8\a\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.octodeck.v1.ItemTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12,\n" +
	"\x05state\x18\x06 \x01(\x0e2\x16.octodeck.v1.ItemStateR\x05state\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12@\n" +
	"\x0elast_synced_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncedAt\x12\x10\n" +
	"\x03url\x18\t \x01(\tR\x03url\x12)\n" +
	"\x06author\x18\n" +
	" \x01(\v2\x11.octodeck.v1.UserR\x06author\x12-\n" +
	"\acommits\x18\v \x03(\v2\x13.octodeck.v1.CommitR\acommits\x120\n" +
	"\bcomments\x18\f \x03(\v2\x14.octodeck.v1.CommentR\bcomments\x12-\n" +
	"\areviews\x18\r \x03(\v2\x13.octodeck.v1.ReviewR\areviews\x12/\n" +
	"\tassignees\x18\x0e \x03(\v2\x11.octodeck.v1.UserR\tassignees\x121\n" +
	"\x05local\x18\x0f \x01(\v2\x1b.octodeck.v1.ItemLocalStateR\x05local\x12\x12\n" +
	"\x04body\x18\x10 \x01(\tR\x04body\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x124\n" +
	"\tmilestone\x18\x12 \x01(\v2\x16.octodeck.v1.MilestoneR\tmilestone\x12*\n" +
	"\x06labels\x18\x13 \x03(\v2\x12.octodeck.v1.LabelR\x06labels\x12:\n" +
	"\fstate_events\x18\x14 \x03(\v2\x17.octodeck.v1.StateEventR\vstateEvents\x12O\n" +
	"\x13viewer_subscription\x18\x15 \x01(\x0e2\x1e.octodeck.v1.SubscriptionStateR\x12viewerSubscription\x12\x19\n" +
	"\bis_draft\x18\x16 \x01(\bR\aisDraft\"\x99\x04\n" +
	"\tSyncTrace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"trace_type\x18\x02 \x01(\tR\ttraceType\x12%\n" +
	"\x0etrigger_source\x18\x03 \x01(\tR\rtriggerSource\x12!\n" +
	"\fquery_string\x18\x04 \x01(\tR\vqueryString\x12'\n" +
	"\x0frepos_evaluated\x18\x05 \x03(\tR\x0ereposEvaluated\x12'\n" +
	"\x0fsince_timestamp\x18\x06 \x01(\tR\x0esinceTimestamp\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12\x1f\n" +
	"\vpages_count\x18\b \x01(\x03R\n" +
	"pagesCount\x12#\n" +
	"\ritems_fetched\x18\t \x01(\x03R\fitemsFetched\x12'\n" +
	"\x0fitems_persisted\x18\n" +
	" \x01(\x03R\x0eitemsPersisted\x120\n" +
	"\x14rate_limit_remaining\x18\v \x01(\x05R\x12rateLimitRemaining\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vraw_payload\x18\r \x01(\tR\n" +
	"rawPayload\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*R\n" +
	"\bItemType\x12\x19\n" +
	"\x15ITEM_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fITEM_TYPE_ISSUE\x10\x01\x12\x10\n" +
	"\fITEM_TYPE_PR\x10\x02\x1a\x04:\x02\x10\x01*j\n" +
	"\tItemState\x12\x1a\n" +
	"\x16ITEM_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fITEM_STATE_OPEN\x10\x01\x12\x15\n" +
	"\x11ITEM_STATE_CLOSED\x10\x02\x12\x15\n" +
	"\x11ITEM_STATE_MERGED\x10\x03*L\n" +
	"\bUserType\x12\x19\n" +
	"\x15USER_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_TYPE_USER\x10\x01\x12\x11\n" +
	"\rUSER_TYPE_BOT\x10\x02*\xba\x01\n" +
	"\n" +
	"ItemStatus\x12\x1b\n" +
	"\x17ITEM_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fITEM_STATUS_NEW\x10\x01\x12\x14\n" +
	"\x10ITEM_STATUS_IDLE\x10\x02\x12\x1c\n" +
	"\x18ITEM_STATUS_NEW_ACTIVITY\x10\x03\x12\x18\n" +
	"\x14ITEM_STATUS_NEW_CODE\x10\x04\x12\x15\n" +
	"\x11ITEM_STATUS_ACKED\x10\x05\x12\x15\n" +
	"\x11ITEM_STATUS_NOISE\x10\x06*\x85\x01\n" +
	"\x10CommentNoiseType\x12\"\n" +
	"\x1eCOMMENT_NOISE_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dCOMMENT_NOISE_TYPE_BOT_AUTHOR\x10\x01\x12$\n" +
	" COMMENT_NOISE_TYPE_SLASH_COMMAND\x10\x02\x1a\x04:\x02\x10\x01*\xb6\x01\n" +
	"\x0fStateChangeType\x12!\n" +
	"\x1dSTATE_CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18STATE_CHANGE_TYPE_CLOSED\x10\x01\x12\x1c\n" +
	"\x18STATE_CHANGE_TYPE_MERGED\x10\x02\x12\x1e\n" +
	"\x1aSTATE_CHANGE_TYPE_REOPENED\x10\x03\x12\x1e\n" +
	"\x1aSTATE_CHANGE_TYPE_ASSIGNED\x10\x04\x1a\x04:\x02\x10\x01*\xa5\x01\n" +
	"\x11SubscriptionState\x12\"\n" +
	"\x1eSUBSCRIPTION_STATE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSUBSCRIPTION_STATE_SUBSCRIBED\x10\x01\x12#\n" +
	"\x1fSUBSCRIPTION_STATE_UNSUBSCRIBED\x10\x02\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATE_IGNORED\x10\x03\x1a\x04:\x02\x10\x01B\xb9\x01\n" +
	"\x0fcom.octodeck.v1B\x0eResourcesProtoP\x01ZIgithub.com/tallclair/octodeck/backend/internal/api/octodeck/v1;octodeckv1\xa2\x02\x03OXX\xaa\x02\vOctodeck.V1\xca\x02\vOctodeck\\V1\xe2\x02\x17Octodeck\\V1\\GPBMetadata\xea\x02\fOctodeck::V1b\beditionsp\xe8\a"

var file_octodeck_v1_resources_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_octodeck_v1_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_octodeck_v1_resources_proto_goTypes = []any{
	(ItemType)(0),                 // 0: octodeck.v1.ItemType
	(ItemState)(0),                // 1: octodeck.v1.ItemState
	(UserType)(0),                 // 2: octodeck.v1.UserType
	(ItemStatus)(0),               // 3: octodeck.v1.ItemStatus
	(CommentNoiseType)(0),         // 4: octodeck.v1.CommentNoiseType
	(StateChangeType)(0),          // 5: octodeck.v1.StateChangeType
	(SubscriptionState)(0),        // 6: octodeck.v1.SubscriptionState
	(*User)(nil),                  // 7: octodeck.v1.User
	(*Comment)(nil),               // 8: octodeck.v1.Comment
	(*ReviewComment)(nil),         // 9: octodeck.v1.ReviewComment
	(*Review)(nil),                // 10: octodeck.v1.Review
	(*Commit)(nil),                // 11: octodeck.v1.Commit
	(*Milestone)(nil),             // 12: octodeck.v1.Milestone
	(*StateEvent)(nil),            // 13: octodeck.v1.StateEvent
	(*Label)(nil),                 // 14: octodeck.v1.Label
	(*ItemLocalState)(nil),        // 15: octodeck.v1.ItemLocalState
	(*Item)(nil),                  // 16: octodeck.v1.Item
	(*SyncTrace)(nil),             // 17: octodeck.v1.SyncTrace
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_octodeck_v1_resources_proto_depIdxs = []int32{
	2,  // 0: octodeck.v1.User.type:type_name -> octodeck.v1.UserType
	18, // 1: octodeck.v1.Comment.created_at:type_name -> google.protobuf.Timestamp
	7,  // 2: octodeck.v1.Comment.author:type_name -> octodeck.v1.User
	4,  // 3: octodeck.v1.Comment.noise_type:type_name -> octodeck.v1.CommentNoiseType
	7,  // 4: octodeck.v1.ReviewComment.author:type_name -> octodeck.v1.User
	18, // 5: octodeck.v1.ReviewComment.created_at:type_name -> google.protobuf.Timestamp
	18, // 6: octodeck.v1.Review.submitted_at:type_name -> google.protobuf.Timestamp
	7,  // 7: octodeck.v1.Review.author:type_name -> octodeck.v1.User
	9,  // 8: octodeck.v1.Review.comments:type_name -> octodeck.v1.ReviewComment
	18, // 9: octodeck.v1.Commit.committed_date:type_name -> google.protobuf.Timestamp
	5,  // 10: octodeck.v1.StateEvent.type:type_name -> octodeck.v1.StateChangeType
	18, // 11: octodeck.v1.StateEvent.created_at:type_name -> google.protobuf.Timestamp
	7,  // 12: octodeck.v1.StateEvent.actor:type_name -> octodeck.v1.User
	3,  // 13: octodeck.v1.ItemLocalState.computed_status:type_name -> octodeck.v1.ItemStatus
	18, // 14: octodeck.v1.ItemLocalState.last_viewed_at:type_name -> google.protobuf.Timestamp
	18, // 15: octodeck.v1.ItemLocalState.acked_at:type_name -> google.protobuf.Timestamp
	0,  // 16: octodeck.v1.Item.type:type_name -> octodeck.v1.ItemType
	1,  // 17: octodeck.v1.Item.state:type_name -> octodeck.v1.ItemState
	18, // 18: octodeck.v1.Item.updated_at:type_name -> google.protobuf.Timestamp
	18, // 19: octodeck.v1.Item.last_synced_at:type_name -> google.protobuf.Timestamp
	7,  // 20: octodeck.v1.Item.author:type_name -> octodeck.v1.User
	11, // 21: octodeck.v1.Item.commits:type_name -> octodeck.v1.Commit
	8,  // 22: octodeck.v1.Item.comments:type_name -> octodeck.v1.Comment
	10, // 23: octodeck.v1.Item.reviews:type_name -> octodeck.v1.Review
	7,  // 24: octodeck.v1.Item.assignees:type_name -> octodeck.v1.User
	15, // 25: octodeck.v1.Item.local:type_name -> octodeck.v1.ItemLocalState
	18, // 26: octodeck.v1.Item.created_at:type_name -> google.protobuf.Timestamp
	12, // 27: octodeck.v1.Item.milestone:type_name -> octodeck.v1.Milestone
	14, // 28: octodeck.v1.Item.labels:type_name -> octodeck.v1.Label
	13, // 29: octodeck.v1.Item.state_events:type_name -> octodeck.v1.StateEvent
	6,  // 30: octodeck.v1.Item.viewer_subscription:type_name -> octodeck.v1.SubscriptionState
	18, // 31: octodeck.v1.SyncTrace.created_at:type_name -> google.protobuf.Timestamp
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_octodeck_v1_resources_proto_init() }
func file_octodeck_v1_resources_proto_init() {
	if File_octodeck_v1_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_octodeck_v1_resources_proto_rawDesc), len(file_octodeck_v1_resources_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_octodeck_v1_resources_proto_goTypes,
		DependencyIndexes: file_octodeck_v1_resources_proto_depIdxs,
		EnumInfos:         file_octodeck_v1_resources_proto_enumTypes,
		MessageInfos:      file_octodeck_v1_resources_proto_msgTypes,
	}.Build()
	File_octodeck_v1_resources_proto = out.File
	file_octodeck_v1_resources_proto_goTypes = nil
	file_octodeck_v1_resources_proto_depIdxs = nil
}
