// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: octodeck/v1/service.proto

package octodeckv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/tallclair/octodeck/backend/internal/api/octodeck/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OctoDeckServiceName is the fully-qualified name of the OctoDeckService service.
	OctoDeckServiceName = "octodeck.v1.OctoDeckService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OctoDeckServiceGetItemsProcedure is the fully-qualified name of the OctoDeckService's GetItems
	// RPC.
	OctoDeckServiceGetItemsProcedure = "/octodeck.v1.OctoDeckService/GetItems"
	// OctoDeckServiceGetItemProcedure is the fully-qualified name of the OctoDeckService's GetItem RPC.
	OctoDeckServiceGetItemProcedure = "/octodeck.v1.OctoDeckService/GetItem"
	// OctoDeckServiceSyncProcedure is the fully-qualified name of the OctoDeckService's Sync RPC.
	OctoDeckServiceSyncProcedure = "/octodeck.v1.OctoDeckService/Sync"
	// OctoDeckServiceViewItemProcedure is the fully-qualified name of the OctoDeckService's ViewItem
	// RPC.
	OctoDeckServiceViewItemProcedure = "/octodeck.v1.OctoDeckService/ViewItem"
	// OctoDeckServiceAckItemProcedure is the fully-qualified name of the OctoDeckService's AckItem RPC.
	OctoDeckServiceAckItemProcedure = "/octodeck.v1.OctoDeckService/AckItem"
	// OctoDeckServiceStarItemProcedure is the fully-qualified name of the OctoDeckService's StarItem
	// RPC.
	OctoDeckServiceStarItemProcedure = "/octodeck.v1.OctoDeckService/StarItem"
	// OctoDeckServiceSetNotesProcedure is the fully-qualified name of the OctoDeckService's SetNotes
	// RPC.
	OctoDeckServiceSetNotesProcedure = "/octodeck.v1.OctoDeckService/SetNotes"
	// OctoDeckServiceRefetchItemProcedure is the fully-qualified name of the OctoDeckService's
	// RefetchItem RPC.
	OctoDeckServiceRefetchItemProcedure = "/octodeck.v1.OctoDeckService/RefetchItem"
	// OctoDeckServiceDeleteItemProcedure is the fully-qualified name of the OctoDeckService's
	// DeleteItem RPC.
	OctoDeckServiceDeleteItemProcedure = "/octodeck.v1.OctoDeckService/DeleteItem"
	// OctoDeckServiceGetSyncStatusProcedure is the fully-qualified name of the OctoDeckService's
	// GetSyncStatus RPC.
	OctoDeckServiceGetSyncStatusProcedure = "/octodeck.v1.OctoDeckService/GetSyncStatus"
	// OctoDeckServiceGetSyncTracesProcedure is the fully-qualified name of the OctoDeckService's
	// GetSyncTraces RPC.
	OctoDeckServiceGetSyncTracesProcedure = "/octodeck.v1.OctoDeckService/GetSyncTraces"
	// OctoDeckServiceGetDatabaseStatsProcedure is the fully-qualified name of the OctoDeckService's
	// GetDatabaseStats RPC.
	OctoDeckServiceGetDatabaseStatsProcedure = "/octodeck.v1.OctoDeckService/GetDatabaseStats"
	// OctoDeckServiceGetConfigProcedure is the fully-qualified name of the OctoDeckService's GetConfig
	// RPC.
	OctoDeckServiceGetConfigProcedure = "/octodeck.v1.OctoDeckService/GetConfig"
	// OctoDeckServiceUpdateConfigProcedure is the fully-qualified name of the OctoDeckService's
	// UpdateConfig RPC.
	OctoDeckServiceUpdateConfigProcedure = "/octodeck.v1.OctoDeckService/UpdateConfig"
)

// OctoDeckServiceClient is a client for the octodeck.v1.OctoDeckService service.
type OctoDeckServiceClient interface {
	// Main Dashboard Data
	GetItems(context.Context, *connect.Request[v1.GetItemsRequest]) (*connect.Response[v1.GetItemsResponse], error)
	GetItem(context.Context, *connect.Request[v1.GetItemRequest]) (*connect.Response[v1.GetItemResponse], error)
	// Synchronization (Streaming)
	Sync(context.Context, *connect.Request[v1.SyncRequest]) (*connect.ServerStreamForClient[v1.SyncResponse], error)
	// Actions
	ViewItem(context.Context, *connect.Request[v1.ViewItemRequest]) (*connect.Response[v1.ViewItemResponse], error)
	AckItem(context.Context, *connect.Request[v1.AckItemRequest]) (*connect.Response[v1.AckItemResponse], error)
	StarItem(context.Context, *connect.Request[v1.StarItemRequest]) (*connect.Response[v1.StarItemResponse], error)
	SetNotes(context.Context, *connect.Request[v1.SetNotesRequest]) (*connect.Response[v1.SetNotesResponse], error)
	RefetchItem(context.Context, *connect.Request[v1.RefetchItemRequest]) (*connect.Response[v1.RefetchItemResponse], error)
	DeleteItem(context.Context, *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error)
	// Synchronization Status & Traces
	GetSyncStatus(context.Context, *connect.Request[v1.GetSyncStatusRequest]) (*connect.Response[v1.GetSyncStatusResponse], error)
	GetSyncTraces(context.Context, *connect.Request[v1.GetSyncTracesRequest]) (*connect.Response[v1.GetSyncTracesResponse], error)
	// Database & Storage Observability
	GetDatabaseStats(context.Context, *connect.Request[v1.GetDatabaseStatsRequest]) (*connect.Response[v1.GetDatabaseStatsResponse], error)
	// Configuration
	GetConfig(context.Context, *connect.Request[v1.GetConfigRequest]) (*connect.Response[v1.GetConfigResponse], error)
	UpdateConfig(context.Context, *connect.Request[v1.UpdateConfigRequest]) (*connect.Response[v1.UpdateConfigResponse], error)
}

// NewOctoDeckServiceClient constructs a client for the octodeck.v1.OctoDeckService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOctoDeckServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OctoDeckServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	octoDeckServiceMethods := v1.File_octodeck_v1_service_proto.Services().ByName("OctoDeckService").Methods()
	return &octoDeckServiceClient{
		getItems: connect.NewClient[v1.GetItemsRequest, v1.GetItemsResponse](
			httpClient,
			baseURL+OctoDeckServiceGetItemsProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("GetItems")),
			connect.WithClientOptions(opts...),
		),
		getItem: connect.NewClient[v1.GetItemRequest, v1.GetItemResponse](
			httpClient,
			baseURL+OctoDeckServiceGetItemProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("GetItem")),
			connect.WithClientOptions(opts...),
		),
		sync: connect.NewClient[v1.SyncRequest, v1.SyncResponse](
			httpClient,
			baseURL+OctoDeckServiceSyncProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("Sync")),
			connect.WithClientOptions(opts...),
		),
		viewItem: connect.NewClient[v1.ViewItemRequest, v1.ViewItemResponse](
			httpClient,
			baseURL+OctoDeckServiceViewItemProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("ViewItem")),
			connect.WithClientOptions(opts...),
		),
		ackItem: connect.NewClient[v1.AckItemRequest, v1.AckItemResponse](
			httpClient,
			baseURL+OctoDeckServiceAckItemProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("AckItem")),
			connect.WithClientOptions(opts...),
		),
		starItem: connect.NewClient[v1.StarItemRequest, v1.StarItemResponse](
			httpClient,
			baseURL+OctoDeckServiceStarItemProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("StarItem")),
			connect.WithClientOptions(opts...),
		),
		setNotes: connect.NewClient[v1.SetNotesRequest, v1.SetNotesResponse](
			httpClient,
			baseURL+OctoDeckServiceSetNotesProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("SetNotes")),
			connect.WithClientOptions(opts...),
		),
		refetchItem: connect.NewClient[v1.RefetchItemRequest, v1.RefetchItemResponse](
			httpClient,
			baseURL+OctoDeckServiceRefetchItemProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("RefetchItem")),
			connect.WithClientOptions(opts...),
		),
		deleteItem: connect.NewClient[v1.DeleteItemRequest, v1.DeleteItemResponse](
			httpClient,
			baseURL+OctoDeckServiceDeleteItemProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("DeleteItem")),
			connect.WithClientOptions(opts...),
		),
		getSyncStatus: connect.NewClient[v1.GetSyncStatusRequest, v1.GetSyncStatusResponse](
			httpClient,
			baseURL+OctoDeckServiceGetSyncStatusProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("GetSyncStatus")),
			connect.WithClientOptions(opts...),
		),
		getSyncTraces: connect.NewClient[v1.GetSyncTracesRequest, v1.GetSyncTracesResponse](
			httpClient,
			baseURL+OctoDeckServiceGetSyncTracesProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("GetSyncTraces")),
			connect.WithClientOptions(opts...),
		),
		getDatabaseStats: connect.NewClient[v1.GetDatabaseStatsRequest, v1.GetDatabaseStatsResponse](
			httpClient,
			baseURL+OctoDeckServiceGetDatabaseStatsProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("GetDatabaseStats")),
			connect.WithClientOptions(opts...),
		),
		getConfig: connect.NewClient[v1.GetConfigRequest, v1.GetConfigResponse](
			httpClient,
			baseURL+OctoDeckServiceGetConfigProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("GetConfig")),
			connect.WithClientOptions(opts...),
		),
		updateConfig: connect.NewClient[v1.UpdateConfigRequest, v1.UpdateConfigResponse](
			httpClient,
			baseURL+OctoDeckServiceUpdateConfigProcedure,
			connect.WithSchema(octoDeckServiceMethods.ByName("UpdateConfig")),
			connect.WithClientOptions(opts...),
		),
	}
}

// octoDeckServiceClient implements OctoDeckServiceClient.
type octoDeckServiceClient struct {
	getItems         *connect.Client[v1.GetItemsRequest, v1.GetItemsResponse]
	getItem          *connect.Client[v1.GetItemRequest, v1.GetItemResponse]
	sync             *connect.Client[v1.SyncRequest, v1.SyncResponse]
	viewItem         *connect.Client[v1.ViewItemRequest, v1.ViewItemResponse]
	ackItem          *connect.Client[v1.AckItemRequest, v1.AckItemResponse]
	starItem         *connect.Client[v1.StarItemRequest, v1.StarItemResponse]
	setNotes         *connect.Client[v1.SetNotesRequest, v1.SetNotesResponse]
	refetchItem      *connect.Client[v1.RefetchItemRequest, v1.RefetchItemResponse]
	deleteItem       *connect.Client[v1.DeleteItemRequest, v1.DeleteItemResponse]
	getSyncStatus    *connect.Client[v1.GetSyncStatusRequest, v1.GetSyncStatusResponse]
	getSyncTraces    *connect.Client[v1.GetSyncTracesRequest, v1.GetSyncTracesResponse]
	getDatabaseStats *connect.Client[v1.GetDatabaseStatsRequest, v1.GetDatabaseStatsResponse]
	getConfig        *connect.Client[v1.GetConfigRequest, v1.GetConfigResponse]
	updateConfig     *connect.Client[v1.UpdateConfigRequest, v1.UpdateConfigResponse]
}

// GetItems calls octodeck.v1.OctoDeckService.GetItems.
func (c *octoDeckServiceClient) GetItems(ctx context.Context, req *connect.Request[v1.GetItemsRequest]) (*connect.Response[v1.GetItemsResponse], error) {
	return c.getItems.CallUnary(ctx, req)
}

// GetItem calls octodeck.v1.OctoDeckService.GetItem.
func (c *octoDeckServiceClient) GetItem(ctx context.Context, req *connect.Request[v1.GetItemRequest]) (*connect.Response[v1.GetItemResponse], error) {
	return c.getItem.CallUnary(ctx, req)
}

// Sync calls octodeck.v1.OctoDeckService.Sync.
func (c *octoDeckServiceClient) Sync(ctx context.Context, req *connect.Request[v1.SyncRequest]) (*connect.ServerStreamForClient[v1.SyncResponse], error) {
	return c.sync.CallServerStream(ctx, req)
}

// ViewItem calls octodeck.v1.OctoDeckService.ViewItem.
func (c *octoDeckServiceClient) ViewItem(ctx context.Context, req *connect.Request[v1.ViewItemRequest]) (*connect.Response[v1.ViewItemResponse], error) {
	return c.viewItem.CallUnary(ctx, req)
}

// AckItem calls octodeck.v1.OctoDeckService.AckItem.
func (c *octoDeckServiceClient) AckItem(ctx context.Context, req *connect.Request[v1.AckItemRequest]) (*connect.Response[v1.AckItemResponse], error) {
	return c.ackItem.CallUnary(ctx, req)
}

// StarItem calls octodeck.v1.OctoDeckService.StarItem.
func (c *octoDeckServiceClient) StarItem(ctx context.Context, req *connect.Request[v1.StarItemRequest]) (*connect.Response[v1.StarItemResponse], error) {
	return c.starItem.CallUnary(ctx, req)
}

// SetNotes calls octodeck.v1.OctoDeckService.SetNotes.
func (c *octoDeckServiceClient) SetNotes(ctx context.Context, req *connect.Request[v1.SetNotesRequest]) (*connect.Response[v1.SetNotesResponse], error) {
	return c.setNotes.CallUnary(ctx, req)
}

// RefetchItem calls octodeck.v1.OctoDeckService.RefetchItem.
func (c *octoDeckServiceClient) RefetchItem(ctx context.Context, req *connect.Request[v1.RefetchItemRequest]) (*connect.Response[v1.RefetchItemResponse], error) {
	return c.refetchItem.CallUnary(ctx, req)
}

// DeleteItem calls octodeck.v1.OctoDeckService.DeleteItem.
func (c *octoDeckServiceClient) DeleteItem(ctx context.Context, req *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error) {
	return c.deleteItem.CallUnary(ctx, req)
}

// GetSyncStatus calls octodeck.v1.OctoDeckService.GetSyncStatus.
func (c *octoDeckServiceClient) GetSyncStatus(ctx context.Context, req *connect.Request[v1.GetSyncStatusRequest]) (*connect.Response[v1.GetSyncStatusResponse], error) {
	return c.getSyncStatus.CallUnary(ctx, req)
}

// GetSyncTraces calls octodeck.v1.OctoDeckService.GetSyncTraces.
func (c *octoDeckServiceClient) GetSyncTraces(ctx context.Context, req *connect.Request[v1.GetSyncTracesRequest]) (*connect.Response[v1.GetSyncTracesResponse], error) {
	return c.getSyncTraces.CallUnary(ctx, req)
}

// GetDatabaseStats calls octodeck.v1.OctoDeckService.GetDatabaseStats.
func (c *octoDeckServiceClient) GetDatabaseStats(ctx context.Context, req *connect.Request[v1.GetDatabaseStatsRequest]) (*connect.Response[v1.GetDatabaseStatsResponse], error) {
	return c.getDatabaseStats.CallUnary(ctx, req)
}

// GetConfig calls octodeck.v1.OctoDeckService.GetConfig.
func (c *octoDeckServiceClient) GetConfig(ctx context.Context, req *connect.Request[v1.GetConfigRequest]) (*connect.Response[v1.GetConfigResponse], error) {
	return c.getConfig.CallUnary(ctx, req)
}

// UpdateConfig calls octodeck.v1.OctoDeckService.UpdateConfig.
func (c *octoDeckServiceClient) UpdateConfig(ctx context.Context, req *connect.Request[v1.UpdateConfigRequest]) (*connect.Response[v1.UpdateConfigResponse], error) {
	return c.updateConfig.CallUnary(ctx, req)
}

// OctoDeckServiceHandler is an implementation of the octodeck.v1.OctoDeckService service.
type OctoDeckServiceHandler interface {
	// Main Dashboard Data
	GetItems(context.Context, *connect.Request[v1.GetItemsRequest]) (*connect.Response[v1.GetItemsResponse], error)
	GetItem(context.Context, *connect.Request[v1.GetItemRequest]) (*connect.Response[v1.GetItemResponse], error)
	// Synchronization (Streaming)
	Sync(context.Context, *connect.Request[v1.SyncRequest], *connect.ServerStream[v1.SyncResponse]) error
	// Actions
	ViewItem(context.Context, *connect.Request[v1.ViewItemRequest]) (*connect.Response[v1.ViewItemResponse], error)
	AckItem(context.Context, *connect.Request[v1.AckItemRequest]) (*connect.Response[v1.AckItemResponse], error)
	StarItem(context.Context, *connect.Request[v1.StarItemRequest]) (*connect.Response[v1.StarItemResponse], error)
	SetNotes(context.Context, *connect.Request[v1.SetNotesRequest]) (*connect.Response[v1.SetNotesResponse], error)
	RefetchItem(context.Context, *connect.Request[v1.RefetchItemRequest]) (*connect.Response[v1.RefetchItemResponse], error)
	DeleteItem(context.Context, *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error)
	// Synchronization Status & Traces
	GetSyncStatus(context.Context, *connect.Request[v1.GetSyncStatusRequest]) (*connect.Response[v1.GetSyncStatusResponse], error)
	GetSyncTraces(context.Context, *connect.Request[v1.GetSyncTracesRequest]) (*connect.Response[v1.GetSyncTracesResponse], error)
	// Database & Storage Observability
	GetDatabaseStats(context.Context, *connect.Request[v1.GetDatabaseStatsRequest]) (*connect.Response[v1.GetDatabaseStatsResponse], error)
	// Configuration
	GetConfig(context.Context, *connect.Request[v1.GetConfigRequest]) (*connect.Response[v1.GetConfigResponse], error)
	UpdateConfig(context.Context, *connect.Request[v1.UpdateConfigRequest]) (*connect.Response[v1.UpdateConfigResponse], error)
}

// NewOctoDeckServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOctoDeckServiceHandler(svc OctoDeckServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	octoDeckServiceMethods := v1.File_octodeck_v1_service_proto.Services().ByName("OctoDeckService").Methods()
	octoDeckServiceGetItemsHandler := connect.NewUnaryHandler(
		OctoDeckServiceGetItemsProcedure,
		svc.GetItems,
		connect.WithSchema(octoDeckServiceMethods.ByName("GetItems")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceGetItemHandler := connect.NewUnaryHandler(
		OctoDeckServiceGetItemProcedure,
		svc.GetItem,
		connect.WithSchema(octoDeckServiceMethods.ByName("GetItem")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceSyncHandler := connect.NewServerStreamHandler(
		OctoDeckServiceSyncProcedure,
		svc.Sync,
		connect.WithSchema(octoDeckServiceMethods.ByName("Sync")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceViewItemHandler := connect.NewUnaryHandler(
		OctoDeckServiceViewItemProcedure,
		svc.ViewItem,
		connect.WithSchema(octoDeckServiceMethods.ByName("ViewItem")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceAckItemHandler := connect.NewUnaryHandler(
		OctoDeckServiceAckItemProcedure,
		svc.AckItem,
		connect.WithSchema(octoDeckServiceMethods.ByName("AckItem")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceStarItemHandler := connect.NewUnaryHandler(
		OctoDeckServiceStarItemProcedure,
		svc.StarItem,
		connect.WithSchema(octoDeckServiceMethods.ByName("StarItem")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceSetNotesHandler := connect.NewUnaryHandler(
		OctoDeckServiceSetNotesProcedure,
		svc.SetNotes,
		connect.WithSchema(octoDeckServiceMethods.ByName("SetNotes")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceRefetchItemHandler := connect.NewUnaryHandler(
		OctoDeckServiceRefetchItemProcedure,
		svc.RefetchItem,
		connect.WithSchema(octoDeckServiceMethods.ByName("RefetchItem")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceDeleteItemHandler := connect.NewUnaryHandler(
		OctoDeckServiceDeleteItemProcedure,
		svc.DeleteItem,
		connect.WithSchema(octoDeckServiceMethods.ByName("DeleteItem")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceGetSyncStatusHandler := connect.NewUnaryHandler(
		OctoDeckServiceGetSyncStatusProcedure,
		svc.GetSyncStatus,
		connect.WithSchema(octoDeckServiceMethods.ByName("GetSyncStatus")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceGetSyncTracesHandler := connect.NewUnaryHandler(
		OctoDeckServiceGetSyncTracesProcedure,
		svc.GetSyncTraces,
		connect.WithSchema(octoDeckServiceMethods.ByName("GetSyncTraces")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceGetDatabaseStatsHandler := connect.NewUnaryHandler(
		OctoDeckServiceGetDatabaseStatsProcedure,
		svc.GetDatabaseStats,
		connect.WithSchema(octoDeckServiceMethods.ByName("GetDatabaseStats")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceGetConfigHandler := connect.NewUnaryHandler(
		OctoDeckServiceGetConfigProcedure,
		svc.GetConfig,
		connect.WithSchema(octoDeckServiceMethods.ByName("GetConfig")),
		connect.WithHandlerOptions(opts...),
	)
	octoDeckServiceUpdateConfigHandler := connect.NewUnaryHandler(
		OctoDeckServiceUpdateConfigProcedure,
		svc.UpdateConfig,
		connect.WithSchema(octoDeckServiceMethods.ByName("UpdateConfig")),
		connect.WithHandlerOptions(opts...),
	)
	return "/octodeck.v1.OctoDeckService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OctoDeckServiceGetItemsProcedure:
			octoDeckServiceGetItemsHandler.ServeHTTP(w, r)
		case OctoDeckServiceGetItemProcedure:
			octoDeckServiceGetItemHandler.ServeHTTP(w, r)
		case OctoDeckServiceSyncProcedure:
			octoDeckServiceSyncHandler.ServeHTTP(w, r)
		case OctoDeckServiceViewItemProcedure:
			octoDeckServiceViewItemHandler.ServeHTTP(w, r)
		case OctoDeckServiceAckItemProcedure:
			octoDeckServiceAckItemHandler.ServeHTTP(w, r)
		case OctoDeckServiceStarItemProcedure:
			octoDeckServiceStarItemHandler.ServeHTTP(w, r)
		case OctoDeckServiceSetNotesProcedure:
			octoDeckServiceSetNotesHandler.ServeHTTP(w, r)
		case OctoDeckServiceRefetchItemProcedure:
			octoDeckServiceRefetchItemHandler.ServeHTTP(w, r)
		case OctoDeckServiceDeleteItemProcedure:
			octoDeckServiceDeleteItemHandler.ServeHTTP(w, r)
		case OctoDeckServiceGetSyncStatusProcedure:
			octoDeckServiceGetSyncStatusHandler.ServeHTTP(w, r)
		case OctoDeckServiceGetSyncTracesProcedure:
			octoDeckServiceGetSyncTracesHandler.ServeHTTP(w, r)
		case OctoDeckServiceGetDatabaseStatsProcedure:
			octoDeckServiceGetDatabaseStatsHandler.ServeHTTP(w, r)
		case OctoDeckServiceGetConfigProcedure:
			octoDeckServiceGetConfigHandler.ServeHTTP(w, r)
		case OctoDeckServiceUpdateConfigProcedure:
			octoDeckServiceUpdateConfigHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOctoDeckServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOctoDeckServiceHandler struct{}

func (UnimplementedOctoDeckServiceHandler) GetItems(context.Context, *connect.Request[v1.GetItemsRequest]) (*connect.Response[v1.GetItemsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.GetItems is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) GetItem(context.Context, *connect.Request[v1.GetItemRequest]) (*connect.Response[v1.GetItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.GetItem is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) Sync(context.Context, *connect.Request[v1.SyncRequest], *connect.ServerStream[v1.SyncResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.Sync is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) ViewItem(context.Context, *connect.Request[v1.ViewItemRequest]) (*connect.Response[v1.ViewItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.ViewItem is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) AckItem(context.Context, *connect.Request[v1.AckItemRequest]) (*connect.Response[v1.AckItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.AckItem is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) StarItem(context.Context, *connect.Request[v1.StarItemRequest]) (*connect.Response[v1.StarItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.StarItem is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) SetNotes(context.Context, *connect.Request[v1.SetNotesRequest]) (*connect.Response[v1.SetNotesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.SetNotes is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) RefetchItem(context.Context, *connect.Request[v1.RefetchItemRequest]) (*connect.Response[v1.RefetchItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.RefetchItem is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) DeleteItem(context.Context, *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.DeleteItem is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) GetSyncStatus(context.Context, *connect.Request[v1.GetSyncStatusRequest]) (*connect.Response[v1.GetSyncStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.GetSyncStatus is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) GetSyncTraces(context.Context, *connect.Request[v1.GetSyncTracesRequest]) (*connect.Response[v1.GetSyncTracesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.GetSyncTraces is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) GetDatabaseStats(context.Context, *connect.Request[v1.GetDatabaseStatsRequest]) (*connect.Response[v1.GetDatabaseStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.GetDatabaseStats is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) GetConfig(context.Context, *connect.Request[v1.GetConfigRequest]) (*connect.Response[v1.GetConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.GetConfig is not implemented"))
}

func (UnimplementedOctoDeckServiceHandler) UpdateConfig(context.Context, *connect.Request[v1.UpdateConfigRequest]) (*connect.Response[v1.UpdateConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octodeck.v1.OctoDeckService.UpdateConfig is not implemented"))
}
